
const preselected_variables = [
    'age_at_baseline',
    'adopted',
    'twin',
    'birthplace',
    'birthplace_mom',
    'birthplace_dad',
    'participant_race',
    'nih_ethnic_cat',
    'age_mom',
    'age_dad',
    'FMP',
    'ROCYN15',
    'RTOCYRS15',
    'EVPRG',
    'AGEFFTP',
    'TOTPRG',
    'RMENOVARC',
    'HEIGHTX',
    'WEIGHTX',
    'bmi',
    'DIABSELF',
    'HIPFSELF',
    'SPMP3YR',
    'SPMHRLT',
    'vitgrp',
    'ALCYRC',
    'SMKEXP',
    'TYRSSMK',
    'AVGCIGDY',
    'TPACKYRS',
];

export default preselected_variables;
