
const preselected_variables = [
    "age_at_baseline",
    "adopted",
    "twin",
    "birthplace",
    "birthplace_mom",
    "birthplace_dad",
    "participant_race",
    "nih_ethnic_cat",
    "age_mom_atbirth",
    "age_dad_atbirth",
    "menarche_age",
    "oralcntr_ever_q1",
    "oralcntr_yrs",
    "fullterm_age1st",
    "preg_ever_q1",
    "preg_total_q1",
    "meno_stattype",
    "height_q1",
    "weight_q1",
    "bmi_q1",
    "diab_self_q1",
    "hbp_self_q1",
    "allex_hrs_q1",
    "allex_life_hrs",
    "vit_mulvit_q1",
    "alchl_analyscat",
    "smoke_expocat",
    "smoke_totyrs",
    "smoke_totpackyrs",
    "cig_day_avg",
];

export default preselected_variables;
