let site_groups_name = [
    'Lip',
    'Tongue',
    'Salivary Gland',
    'Floor of Mouth',
    'Gum and Other Mouth',
    'Nasopharynx',
    'Tonsil',
    'Oropharynx',
    'Hypopharynx',
    'Other Oral Cavity and Pharynx',
    'Esophagus',
    'Stomach',
    'Small Intestine',
    'Cecum',
    'Appendix',
    'Ascending Colon',
    'Hepatic Flexure',
    'Transverse Colon',
    'Splenic Flexure',
    'Descending Colon',
    'Sigmoid Colon',
    'Large Intestine, NOS',
    'Rectosigmoid Junction',
    'Rectum',
    'Anus, Anal Canal and Anorectum',
    'Liver',
    'Intrahepatic Bile Duct',
    'Gallbladder',
    'Other Biliary',
    'Pancreas',
    'Retroperitoneum',
    'Peritoneum, Omentum and Mesentery',
    'Other Digestive Organs',
    'Nose, Nasal Cavity and Middle Ear',
    'Larynx',
    'Lung and Bronchus',
    'Pleura',
    'Trachea, Mediastinum and Other Respirato',
    'Bones and Joints',
    'Soft Tissue including Heart',
    'Melanoma of the Skin',
    'Other Non-Epithelial Skin',
    'Breast',
    'Cervix Uteri',
    'Corpus Uteri',
    'Uterus, NOS',
    'Ovary',
    'Vagina',
    'Vulva',
    'Other Female Genital Organs',
    'Urinary Bladder',
    'Kidney and Renal Pelvis',
    'Ureter',
    'Other Urinary Organs',
    'Eye and Orbit',
    'Brain',
    'Cranial Nerves Other Nervous System',
    'Thyroid',
    'Other Endocrine including Thymus',
    'Hodgkin - Nodal',
    'Hodgkin - Extranodal',
    'NHL - Nodal',
    'NHL - Extranodal',
    'Myeloma',
    'Acute Lymphocytic Leukemia',
    'Chronic Lymphocytic Leukemia',
    'Other Lymphocytic Leukemia',
    'Acute Myeloid Leukemia',
    'Chronic Myeloid Leukemia',
    'Other Myeloid/Monocytic Leukemia',
    'Acute Monocytic Leukemia',
    'Other Acute Leukemia',
    'Aleukemic, subleukemic and NOS',
    'Mesothelioma',
    'Kaposi Sarcoma',
    'Miscellaneous',
];

module.exports = site_groups_name;
