
const users = [
    {"first_name":"Kyle","last_name":"Barber","email":"kbarber@ucsd.edu","role":"user"},
    {"first_name":"David","last_name":"Beitler","email":"dbeitler@sdsc.edu","role":"user"},
    {"first_name":"Brian","last_name":"Hom","email":"bhom@sdsc.edu","role":"user"},
    {"first_name":"Paul","last_name":"Hughes","email":"pahughes@ucsd.edu","role":"user"},
    {"first_name":"Edward","last_name":"Wade","email":"ewade@ucsd.edu","role":"user"},
    {"first_name":"Jim","last_name":"Lacey","email":"jlacey@coh.org","role":"user"},
    {"first_name":"Nadia","last_name":"Chung","email":"nchung@coh.org","role":"user"},
    {"first_name":"Jane","last_name":"Halley","email":"jsullivan-halley@coh.org","role":"user"},
    {"first_name":"Huiyan","last_name":"Ma","email":"hma@coh.org","role":"user"},
    {"first_name":"Rosemary","last_name":"Vazquez","email":"rmvazquez@ucsd.edu","role":"user"},
    {"first_name":"Eunjung","last_name":"Lee","email":"eunjung.lee@med.usc.edu","role":"user"},
    {"first_name":"Susan","last_name":"Neuhausen","email":"sneuhausen@coh.org","role":"user"},
    {"first_name":"Christine","last_name":"Duffy","email":"cduffy@psg.ucsf.edu","role":"user"},
    {"first_name":"Leslie","last_name":"Bernstein","email":"lbernstein@coh.org","role":"user"},
    {"first_name":"Xinxin","last_name":"Xu","email":"xinxu@coh.org","role":"user"},
    {"first_name":"Susan","last_name":"Hurley","email":"susan.hurley@cpic.org","role":"user"},
    {"first_name":"Jenna","last_name":"Voutsinas","email":"jvoutsinas@coh.org","role":"user"},
    {"first_name":"Donna","last_name":"Murdock","email":"dmurdock@coh.org","role":"user"},
    {"first_name":"Kristen","last_name":"Savage","email":"ksavage@coh.org","role":"user"},
    {"first_name":"Rich","last_name":"Pinder","email":"rpinder@usc.edu","role":"user"},
    {"first_name":"Jennifer","last_name":"Benbow","email":"jbenbow@coh.org","role":"user"},
    {"first_name":"Charlie","last_name":"Zhong","email":"czhong@coh.org","role":"user"},
    {"first_name":"Debbie","last_name":"Goldberg","email":"debbie.goldberg@ucsf.edu","role":"user"},
    {"first_name":"Sophia","last_name":"Wang","email":"sowang@coh.org","role":"user"},
    {"first_name":"Tina","last_name":"Clarke","email":"tina@cpic.org","role":"user"},
    {"first_name":"Julie","last_name":"VonBehren","email":"julie.vonbehren@ucsf.edu","role":"user"},
    {"first_name":"Pamela","last_name":"Horn-Ross","email":"pamhornross@gmail.com","role":"user"},
    {"first_name":"Argyrios","last_name":"Ziogas","email":"aziogas@uci.edu","role":"user"},
    {"first_name":"David","last_name":"Nelson","email":"david.nelson@cpic.org","role":"user"},
    {"first_name":"Hoda","last_name":"Anton-Culver","email":"hantoncu@uci.edu","role":"user"},
    {"first_name":"Alison","last_name":"Canchola","email":"alison.canchola@cpic.org","role":"user"},
    {"first_name":"Hannah","last_name":"Park","email":"hlpark@hs.uci.edu","role":"user"},
    {"first_name":"Peggy","last_name":"Reynolds","email":"peggy.reynolds@ucsf.edu","role":"user"},
    {"first_name":"Jessica","last_name":"Clague","email":"jclague@coh.org","role":"user"},
    {"first_name":"Paul","last_name":"Hughes","email":"pahughes@ucsd.edu","role":"user"},
    {"first_name":"Dennis","last_name":"Deapen","email":"ddeapen@usc.edu","role":"user"},
    {"first_name":"Anthony","last_name":"Boyd","email":"awboyd@sdsc.edu","role":"user"},
    {"first_name":"Jess","last_name":"Lella","email":"jlella@tableau.com","role":"user"},
    {"first_name":"Rosemary","last_name":"Test","email":"rmvazquez@ucsd.edu","role":"user"},
    {"first_name":"Tram","last_name":"Lam","email":"lamt@mail.nig.gov","role":"user"},
    {"first_name":"Michelle","last_name":"Dich","email":"mdich@coh.org","role":"user"},
    {"first_name":"Eliza","last_name":"Miller","email":"ecm2137@cumc.columbia.edu","role":"user"},
    {"first_name":"Joshua","last_name":"Willey","email":"jzw2@cumc.columbia.edu","role":"user"},
    {"first_name":"Ying","last_name":"Kuen Cheung","email":"yc632@cumc.columbia.edu","role":"user"},
    {"first_name":"Moon","last_name":"Park","email":"ypm2102@cumc.columbia.edu","role":"user"},
    {"first_name":"Jenny","last_name":"Chang","email":"jjchang@uci.edu","role":"user"},
    {"first_name":"Luohua","last_name":"Jiang","email":"ljiang@s2.internal","role":"user"},
    {"first_name":"Nicole","last_name":"Delgado","email":"nicdelgado@coh.org","role":"user"},
    {"first_name":"Sunita","last_name":"Patel","email":"spatel@s2.internal","role":"user"},
    {"first_name":"Ed","last_name":"Test","email":"ewade@sdsc.edu","role":"user"},
    {"first_name":"Emma","last_name":"Spielfogel","email":"espielfogel@coh.org","role":"user"},
    {"first_name":"April","last_name":"Kinninger","email":"kinninge@usc.edu","role":"user"},
    {"first_name":"Nick","last_name":"Naughton","email":"nnaughto@usc.edu","role":"user"},
    {"first_name":"Brenda","last_name":"Birmann","email":"brenda.birmann@channing.harvard.edu","role":"user"},
    {"first_name":"Ke","last_name":"Wang","email":"nhkew@channing.harvard.edu","role":"user"},
    {"first_name":"Hamdi","last_name":"Abdi","email":"hamdi.abdi@nih.gov","role":"user"},
    {"first_name":"Kirstin","last_name":"Pirie","email":"kirstin.pirie@ndph.ox.ac.uk","role":"user"},
    {"first_name":"Sandra","last_name":"Huffman","email":"shuffman@coh.org","role":"user"},
    {"first_name":"Lorena","last_name":"Pacheco","email":"l2pachec@ucsd.edu","role":"user"},
    {"first_name":"Mihee","last_name":"Lee","email":"ml_322@usc.edu","role":"user"},
    {"first_name":"S. Lani","last_name":"Park","email":"sungship@med.usc.edu","role":"user"},
    {"first_name":"Yaa","last_name":"Klu","email":"ykk2116@cumc.columbia.edu","role":"user"},
    {"first_name":"Natalie","last_name":"Bello","email":"nb338@columbia.edu","role":"user"},
    {"first_name":"Ann","last_name":"Hamilton","email":"ahamilt@med.usc.edu","role":"user"},
    {"first_name":"Loretta","last_name":"Erhunmwunsee","email":"lerhunmwunsee@s2.internal","role":"user"},
    {"first_name":"Lennie","last_name":"Wong","email":"LennieWong@coh.org","role":"user"},
    {"first_name":"Tiffany","last_name":"Sanchez","email":"trs21111@cumc.columbia.edu","role":"user"},
    {"first_name":"Maggie","last_name":"Li","email":"maggieli01u@berkeley.edu","role":"user"},
    {"first_name":"Linda","last_name":"Wu","email":"lwu@s2.internal","role":"user"},
    {"first_name":"Hengrui","last_name":"Hu","email":"hhu@coh.org","role":"user"},
    {"first_name":"Kai","last_name":"Lin","email":"klin@sdsc.edu","role":"user"},
    {"first_name":"Creat","last_name":"Tsou","email":"mtsou@sdsu.edu","role":"user"},
    {"first_name":"Yulu","last_name":"Chen","email":"ychen2793@sdsc.edu","role":"user"},
    {"first_name":"Jian","last_name":"Shen","email":"jis025@ucsd.edu","role":"user"},
    {"first_name":"Haihong","last_name":"Huang","email":"hhuang4@sdsu.edu","role":"user"},
    {"first_name":"Lawrence","last_name":"Kushi","email":"larry.kushi@kp.org","role":"user"},
    {"first_name":"Shelley","last_name":"Tworoger","email":"shelley.tworoger@moffitt.org","role":"user"},
    {"first_name":"Vikram","last_name":"Haridass","email":"vharidas@uci.edu","role":"user"},
    {"first_name":"Ayesha","last_name":"Sherzai","email":"asherzai@llu.edu","role":"user"},
    {"first_name":"Humberto","last_name":"Parada","email":"hparada@sdsu.edu","role":"user"},
    {"first_name":"Rebecca","last_name":"Nelson","email":"rnelson@coh.org","role":"user"},
    {"first_name":"Cynthia","last_name":"Chow","email":"cchow8679@sdsu.edu","role":"user"},
    {"first_name":"Rachelle","last_name":"De Ocampo","email":"rdeocampo@sdsc.edu","role":"user"},
    {"first_name":"Wayne","last_name":"Kepner","email":"wkepner2437@sdsu.edu","role":"user"},
    {"first_name":"Arash","last_name":"Delavar","email":"adelavar@ucsd.edu","role":"user"},
    {"first_name":"Wanda","last_name":"Fitzgerald","email":"WFitzgerald@coh.org","role":"user"},
    {"first_name":"Elaine","last_name":"Crawford","email":"626-218-3066","role":"user"},
    {"first_name":"Jessica","last_name":"DeHart","email":"jessica.dehart@cgu.edu","role":"user"},
    {"first_name":"Sandrah","last_name":"Eckel","email":"eckel@usc.edu","role":"user"},
    {"first_name":"Myles","last_name":"Cockburn","email":"myles.cockburn@ucdenver.edu","role":"user"},
    {"first_name":"Erica","last_name":"Ambeba","email":"eambeba@ucsd.edu","role":"user"},
    {"first_name":"Feng","last_name":"Liu-Smith","email":"liufe@gwu.edu","role":"user"},
    {"first_name":"Emily","last_name":"Blake","email":"efblake@gwu.edu","role":"user"},
    {"first_name":"Purva","last_name":"Jain","email":"puj001@ucsd.edu","role":"user"},
    {"first_name":"Caihong","last_name":"Xia","email":"caihongx@usc.edu","role":"user"},
    {"first_name":"Huiyu","last_name":"Deng","email":"huiyuden@usc.edu","role":"user"},
    {"first_name":"Lihua","last_name":"Liu","email":"lihualiu@usc.edu","role":"user"},
    {"first_name":"Tushondra","last_name":"Thomas","email":"tuthomas@coh.org","role":"user"},
    {"first_name":"Lulu","last_name":"Song","email":"lulusong@usc.edu","role":"user"},
    {"first_name":"Charleen","last_name":"Adams","email":"chaadams@coh.org","role":"user"},
    {"first_name":"Sarah","last_name":"Nunes","email":"snunes@coh.org","role":"user"},
    {"first_name":"Julie","last_name":"Bautista","email":"jubautista@coh.org","role":"user"},
    {"first_name":"Mary","last_name":"Ward","email":"wardm@mail.nih.gov","role":"user"},
    {"first_name":"Rena","last_name":"Jones","email":"rena.jones@nih.gov","role":"user"},
    {"first_name":"Laura","last_name":"Costas","email":"laura.costas.ico@gmail.com","role":"user"},
    {"first_name":"Joy","last_name":"Shi","email":"joy_shi@harvard.edu","role":"user"},
    {"first_name":"Mark","last_name":"Powell","email":"markp@zerobreastcancer.org","role":"user"},
    {"first_name":"Theodore","last_name":"Brasky","email":"theodore.brasky@osumc.edu","role":"user"},
    {"first_name":"Megan","last_name":"Clarke","email":"megan.clarke@nih.gov","role":"user"},
    {"first_name":"Xian-Bo","last_name":"Wu","email":"lfurong@smu.edu.cn","role":"user"},
    {"first_name":"James","last_name":"Gangwisch","email":"james.gangwisch@nyspi.columbia.edu","role":"user"},
    {"first_name":"Nikita","last_name":"Wright","email":"niwright@coh.org","role":"user"},
    {"first_name":"James","last_name":"Koh","email":"james.koh@ucsf.edu","role":"user"},
    {"first_name":"Sarah","last_name":"Jackson","email":"sarah.jackson@nih.gov","role":"user"},
    {"first_name":"Nan","last_name":"Xiao","email":"nan.xiao@sbgenomics.com","role":"user"},
    {"first_name":"Eric","last_name":"Miller","email":"eric.miller2@nih.gov","role":"user"},
    {"first_name":"Joshua","last_name":"Demb","email":"jdemb@ucsd.edu","role":"user"},
    {"first_name":"Forgive","last_name":"Avorgbedor","email":"avorgbe@live.unc.edu","role":"user"},
    {"first_name":"Jeffrey","last_name":"Massin","email":"jeffrey.massin@cgu.edu","role":"user"},
    {"first_name":"Siena","last_name":"Schmitt","email":"siena.rapetti@cgu.edu","role":"user"},
    {"first_name":"Hazel","last_name":"Escusa","email":"hazel.escusa@cgu.edu","role":"user"},
    {"first_name":"Maria","last_name":"Espinoza","email":"mz2697@cumc.columbia.edu","role":"user"},
    {"first_name":"Sarah","last_name":"Tom","email":"st3144@cumc.columbia.edu","role":"user"},
    {"first_name":"Laila","last_name":"Al-Shaar","email":"lalshaar@hsph.harvard.edu","role":"user"},
    {"first_name":"Ruifeng","last_name":"Li","email":"rli@hsph.harvard.edu","role":"user"},
    {"first_name":"Abigail","last_name":"Flory","email":"abigail.flory@nih.gov","role":"user"},
    {"first_name":"Xiaolu","last_name":"Zhang-Gross","email":"azhang@hsph.harvard.edu","role":"user"},
    {"first_name":"Shiaw-Shyuan (Sherry)","last_name":"Yaun","email":"syaun@hsph.harvard.edu","role":"user"},
    {"first_name":"Derek","last_name":"Cridebring","email":"dcridebring@tgen.org","role":"user"},
    {"first_name":"Ilona","last_name":"Kabara","email":"ilona.kabara@nih.gov","role":"user"},
    {"first_name":"Kai","last_name":"Lin","email":"klin@sdsc.edu","role":"user"},
    {"first_name":"Su-Ho","last_name":"Hwang","email":"shwang@deepthinkhealth.com","role":"user"},
    {"first_name":"Grace","last_name":"Aldrovandi","email":"galdrovandi@mednet.ucla.edu","role":"user"},
    {"first_name":"Charleston","last_name":"Chiang","email":"charleston.chiang@med.usc.edu","role":"user"},
    {"first_name":"Migel","last_name":"Dio","email":"migel.dio@berkeley.edu","role":"user"},
    {"first_name":"Caroline","last_name":"Thompson","email":"caroline.thompson@sdsu.edu","role":"user"},
    {"first_name":"Lisa","last_name":"Gallicchio","email":"lisa.gallicchio@nih.gov","role":"user"},
    {"first_name":"Laura","last_name":"Thompson","email":"lkthomps@usc.edu","role":"user"},
    {"first_name":"Sam","last_name":"Wing","email":"swing@coh.org","role":"user"},
];


let all_users = [];
for (var i=0; i<users.length; i++) {
    let found = false;
    for (var j=i+1; j<users.length; j++ ) {
        if (JSON.stringify(users[i]) === JSON.stringify(users[j])) {
            found = true;
        }
    }
    if (!found) {
        all_users.push(users[i]);
    }
}


module.exports = all_users;

