
const users = [
    {"first_name": "SysKyle", "last_name": "Barber", "email": "kbarber@sdsc.edu", "role": "user"},
    {"first_name": "SysDavid", "last_name": "Beitler", "email": "dbeitler@sdsc.edu", "role": "user"},
    {"first_name": "Hua", "last_name": "Uy", "email": "huy@sdsc.edu", "role": "user"},
    {"first_name": "Brian", "last_name": "Hom", "email": "bhom@sdsc.edu", "role": "user"},
    {"first_name": "Erin", "last_name": "Riley", "email": "erin.riley@ucop.edu", "role": "user"},
    {"first_name": "Giesel", "last_name": "Velez", "email": "giesel.velez@ucop.edu", "role": "user"},
    {"first_name": "Irene", "last_name": "Yamamoto", "email": "irene.yamamoto@ucop.edu", "role": "user"},
    {"first_name": "Jerome", "last_name": "Frantz", "email": "jerome.frantz@ucop.edu", "role": "user"},
    {"first_name": "John", "last_name": "Barrett", "email": "john.barrett@ucop.edu", "role": "user"},
    {"first_name": "Ruth", "last_name": "Assily", "email": "ruth.assily@ucop.edu", "role": "user"},
    {"first_name": "Brenda", "last_name": "Lillington", "email": "brenda.lillington@ucop.edu", "role": "user"},
    {"first_name": "Belinda", "last_name": "Manalac", "email": "bmanalac@uci.edu", "role": "user"},
    {"first_name": "Amina", "last_name": "Assefa", "email": "amina.assefa@berkeley.edu", "role": "user"},
    {"first_name": "Christine", "last_name": "Flanders", "email": "cflanders@ucdavis.edu", "role": "user"},
    {"first_name": "Stacey", "last_name": "Waller", "email": "smwaller@ucdavis.edu", "role": "user"},
    {"first_name": "Grant", "last_name": "Fraley", "email": "gfraley@ucsd.edu", "role": "user"},
    {"first_name": "Grant", "last_name": "Fraley - AD", "email": "gfraley@ucsd.edu", "role": "user"},
    {"first_name": "Kristen", "last_name": "Meseck", "email": "kmeseck@ucsd.edu", "role": "user"},
    {"first_name": "Kyle", "last_name": "Barber", "email": "kbarber@ucsd.edu", "role": "user"},
    {"first_name": "Margo", "last_name": "Simpson", "email": "mdsimpson@us.ibm.com", "role": "user"},
    {"first_name": "Hua", "last_name": "Uy", "email": "huy@ucsd.edu", "role": "user"},
    {"first_name": "Mark", "last_name": "Pumphrey", "email": "mpumphrey@ucsd.edu", "role": "user"},
    {"first_name": "Pei-Ru", "last_name": "Chao", "email": "peiru.chao@ucop.edu", "role": "user"},
    {"first_name": "Cindy", "last_name": "Lau", "email": "Cindy.Lau@ucop.edu", "role": "user"},
    {"first_name": "Jason", "last_name": "Heil", "email": "Jason.Heil@ucsf.edu", "role": "user"},
    {"first_name": "Krishna", "last_name": "Mohan-MFT", "email": "Krishna.Mohan@ucop.edu", "role": "user"},
    {"first_name": "Christine", "last_name": "Chiang", "email": "Christine.Chiang@ucop.edu", "role": "user"},
    {"first_name": "Wayde", "last_name": "Gilliam", "email": "wgilliam@ucsd.edu", "role": "user"},
    {
        "first_name": "Christine",
        "last_name": "Bachich",
        "email": "Christine.Bachich@sedgwickcms.com",
        "role": "user"
    },
    {"first_name": "Justin", "last_name": "Detmar", "email": "jdetmar@alliant.com", "role": "user"},
    {"first_name": "Shaunte", "last_name": "Clemons", "email": "Shaunte.Clemons@sedgwickcms.com", "role": "user"},
    {"first_name": "Dana", "last_name": "Santa Cruz", "email": "Dana.SantaCruz@ucop.edu", "role": "user"},
    {"first_name": "Colleen", "last_name": "Connor", "email": "Colleen.Connor@ucop.edu", "role": "user"},
    {"first_name": "Linneth", "last_name": "Cox", "email": "Linneth.Cox@ucop.edu", "role": "user"},
    {"first_name": "Michael", "last_name": "Linder", "email": "Michael.Linder@ucop.edu", "role": "user"},
    {"first_name": "Jenifer", "last_name": "Swann", "email": "jenifer.swann@uci.edu", "role": "user"},
    {"first_name": "Carey", "last_name": "Barker", "email": "Carey.Barker@ucop.edu", "role": "user"},
    {"first_name": "Trish", "last_name": "Dolan", "email": "Patricia.Dolan@ucop.edu", "role": "user"},
    {"first_name": "Anubha", "last_name": "Narang", "email": "anarang1@in.ibm.com", "role": "user"},
    {"first_name": "David", "last_name": "Beitler", "email": "dbeitler@ucsd.edu", "role": "user"},
    {"first_name": "David", "last_name": "Langenberg", "email": "dlangenberg@unicon.net", "role": "user"},
    {"first_name": "Sumana", "last_name": "Banerjee", "email": "sumanabanerjee@in.ibm.com", "role": "user"},
    {"first_name": "Suman", "last_name": "Dawn", "email": "sumandawn@in.ibm.com", "role": "user"},
    {"first_name": "Madhurima", "last_name": "Biswas", "email": "madhurbi@in.ibm.com", "role": "user"},
    {"first_name": "Upkar", "last_name": "Lidder", "email": "ulidder@us.ibm.com", "role": "user"},
    {"first_name": "Michael", "last_name": "Alleman", "email": "michael.alleman@ucop.edu", "role": "user"},
    {"first_name": "Geetanjali", "last_name": "Karki", "email": "gskarki@us.ibm.com", "role": "user"},
    {"first_name": "Cliff", "last_name": "Kai", "email": "chkai@ucdavis.edu", "role": "user"},
    {"first_name": "Shailesh", "last_name": "Pendkar", "email": "spendkar@in.ibm.com", "role": "user"},
    {"first_name": "Krishna", "last_name": "Mohan--2", "email": "Krishna.Mohan@ucop.edu", "role": "user"},
    {"first_name": "Jasper", "last_name": "Schipperijn", "email": "schipperijn@health.sdu.uk", "role": "user"},
    {"first_name": "Marta", "last_name": "Jankowska", "email": "majankowska@ucsd.edu", "role": "user"},
    {"first_name": "Yaron", "last_name": "Kohn", "email": "yaronk@shoesforcrews.com", "role": "user"},
    {"first_name": "Brian", "last_name": "Hom", "email": "bhom@sdsc.edu", "role": "user"},
    {"first_name": "Hua", "last_name": "Uy", "email": "huy@ucsd.edu", "role": "user"},
    {"first_name": "Mark", "last_name": "Pumphrey", "email": "mpumphrey@ucsd.edu", "role": "user"},
    {"first_name": "David", "last_name": "Beitler", "email": "dbeitler@sdsc.edu", "role": "user"},
    {"first_name": "Kyle", "last_name": "Barber", "email": "kbarber@sdsc.edu", "role": "user"},
    {"first_name": "Hua", "last_name": "Uy", "email": "huy@sdsc.edu", "role": "user"},
    {"first_name": "Jessie", "last_name": "Catacutan", "email": "Jessie.Catacutan@ucop.edu", "role": "user"},
    {"first_name": "Edward", "last_name": "Wade", "email": "ewade@ucsd.edu", "role": "user"},
    {"first_name": "Tony", "last_name": "Choe", "email": "TChoe@mednet.ucla.edu", "role": "user"},
    {"first_name": "Dani", "last_name": "Whitehair", "email": "dwhitehair@sdsc.edu", "role": "user"},
    {"first_name": "DeyinAmy", "last_name": "Liao", "email": "DeyinAmy.Liao@ucop.edu", "role": "user"},
    {"first_name": "Nina", "last_name": "Lwai", "email": "Nina.Lwai@ucop.edu", "role": "user"},
    {"first_name": "Harvey", "last_name": "Wong", "email": "Harvey.Wong@ucop.edu", "role": "user"},
    {"first_name": "Marty", "last_name": "Bayer", "email": "Marty.Bayer@ucop.edu", "role": "user"},
    {"first_name": "Paul", "last_name": "Hughes", "email": "pahughes@ucsd.edu", "role": "user"},
    {"first_name": "Nilofeur", "last_name": "Samuel", "email": "nilofeur.samuel@ucop.edu", "role": "user"},
    {"first_name": "Eric", "last_name": "Goldbrener", "email": "eric.goldbrener@ucop.edu", "role": "user"},
    {"first_name": "Raj", "last_name": "Polipalli", "email": "Raj.Polipalli@ucop.edu", "role": "user"},
    {"first_name": "Hooman", "last_name": "Pejman", "email": "Hooman,Pejman@ucop.edu", "role": "user"},
    {"first_name": "Angelique", "last_name": "Warren", "email": "Angelique.Warren@ucop.edu", "role": "user"},
    {"first_name": "Shawn", "last_name": "Lee", "email": "shawlee@mednet.ucla.edu", "role": "user"},
    {"first_name": "Ayan", "last_name": "Patel", "email": "ayangp@uci.edu", "role": "user"},
    {"first_name": "Ghouse", "last_name": "Mohammed", "email": "GMohammed@mednet.ucla.edu", "role": "user"},
    {"first_name": "Ray", "last_name": "Pablo", "email": "pablorp@uci.edu", "role": "user"},
    {"first_name": "Cynthia", "last_name": "Hsu", "email": "Cynthia.Hsu@ucop.edu", "role": "user"},
    {"first_name": "Pikka", "last_name": "Sodhi", "email": "pikka.sodhi@ucop.edu", "role": "user"},
    {"first_name": "Charles", "last_name": "Bookman", "email": "cbookman@ucdavis.edu", "role": "user"},
    {"first_name": "Sree", "last_name": "Tulimilli", "email": "stulimilli@in.ibm.com", "role": "user"},
    {"first_name": "Kevin", "last_name": "Saundry", "email": "kpsaundr@us.ibm.com", "role": "user"},
    {"first_name": "Eric", "last_name": "Fox", "email": "efox@ud4h.com", "role": "user"},
    {"first_name": "Suneeta", "last_name": "Godbole", "email": "sgodbole@ucsd.edu", "role": "user"},
    {"first_name": "Eileen", "last_name": "Johnson", "email": "e3johnson@ucsd.edu", "role": "user"},
    {"first_name": "Benoit", "last_name": "Thierry", "email": "benoit.thierry@crchum.qc.ca", "role": "user"},
    {"first_name": "Tom", "last_name": "Stewart", "email": "tom.stewart@aut.ac.nz", "role": "user"},
    {"first_name": "Charlie", "last_name": "Soon", "email": "CSoon@mednet.ucla.edu", "role": "user"},
    {"first_name": "Adam", "last_name": "Dowlah", "email": "adowlah@mednet.ucla.edu", "role": "user"},
    {"first_name": "Scott", "last_name": "Bailey", "email": "sbailey@mednet.ucla.edu", "role": "user"},
    {"first_name": "Mohammad", "last_name": "Asad", "email": "masad@mednet.ucla.edu ", "role": "user"},
    {"first_name": "Dani", "last_name": "Whitehair", "email": "dwhitehair@ucsd.edu", "role": "user"},
    {"first_name": "Carolyn", "last_name": "Germino", "email": "cbgermino@ucdavis.edu", "role": "user"},
    {"first_name": "Evan", "last_name": "Katsurani", "email": "egkatsuranis@ucdavis.edu", "role": "user"},
    {"first_name": "Matt", "last_name": "Helms", "email": "shelms@ucdavis.edu", "role": "user"},
    {"first_name": "Pradeep", "last_name": "Haldiya", "email": "phaldiya@ucdavis.edu", "role": "user"},
    {"first_name": "Walter", "last_name": "Sysko", "email": "wsysko@ucdavis.edu", "role": "user"},
    {"first_name": "Norman", "last_name": "Chan", "email": "norchan@ucdavis.edu", "role": "user"},
    {"first_name": "Jay", "last_name": "Ballinger", "email": "jayballinger@ucdavis.edu", "role": "user"},
    {"first_name": "Huiyan", "last_name": "Ma", "email": "hma@coh.org", "role": "user"},
    {"first_name": "Jane", "last_name": "Sullivan-Halley", "email": "jsullivan-halley@coh.org", "role": "user"},
    {"first_name": "Jim", "last_name": "Lacey", "email": "jlacey@coh.org", "role": "user"},
    {"first_name": "Patrick", "last_name": "Rogers", "email": "Patrick.Rogers@ucop.edu", "role": "user"},
    {
        "first_name": "Elena",
        "last_name": "Tolpygo Cranley",
        "email": "Elena.TolpygoCranley@ucop.edu",
        "role": "user"
    },
    {"first_name": "Ken", "last_name": "Lumnaokrut", "email": "Ken.Lumnaokrut@ucop.edu", "role": "user"},
    {"first_name": "Judy", "last_name": "Thai", "email": "Judy.Thai@ucop.edu", "role": "user"},
    {"first_name": "Daniel", "last_name": "Quach", "email": "daquach@ucsd.edu", "role": "user"},
    {"first_name": "Hima", "last_name": "Patlolla", "email": "hima.patlolla@ucop.edu", "role": "user"},
    {"first_name": "Shaifali", "last_name": "Singla", "email": "shaifali.singla@ucop.edu", "role": "user"},
    {"first_name": "Reza", "last_name": "Enayati", "email": "renayati@mednet.ucla.edu", "role": "user"},
    {"first_name": "Ed", "last_name": "Wade", "email": "ewade@sdsc.edu", "role": "user"},
    {"first_name": "Jim", "last_name": "Lacey", "email": "jlacey@coh.org", "role": "user"},
    {"first_name": "Nadia", "last_name": "Chung", "email": "nchung@coh.org", "role": "user"},
    {"first_name": "Jane", "last_name": "Halley", "email": "jsullivan-halley@coh.org", "role": "user"},
    {"first_name": "Huiyan", "last_name": "Ma", "email": "hma@coh.org", "role": "user"},
    {"first_name": "Nadia", "last_name": "Chung", "email": "nchung@coh.org", "role": "user"},
    {"first_name": "Rich", "last_name": "Pinder", "email": "rpinder@usc.edu", "role": "user"},
    {"first_name": "Kristen", "last_name": "Savage", "email": "ksavage@coh.org", "role": "user"},
    {"first_name": "Alison", "last_name": "Canchola", "email": "alison.canchola@cpic.org", "role": "user"},
    {"first_name": "Argyrios", "last_name": "Ziogas", "email": "aziogas@uci.edu", "role": "user"},
    {"first_name": "Christine", "last_name": "Duffy", "email": "cduffy@psg.ucsf.edu", "role": "user"},
    {"first_name": "David", "last_name": "Nelson", "email": "david.nelson@cpic.org", "role": "user"},
    {"first_name": "Dennis", "last_name": "Deapen", "email": "ddeapen@usc.edu", "role": "user"},
    {"first_name": "Donna", "last_name": "Murdock", "email": "dmurdock@coh.org", "role": "user"},
    {"first_name": "Hannah", "last_name": "Park", "email": "hlpark@hs.uci.edu", "role": "user"},
    {"first_name": "Hoda", "last_name": "Anton-Culver", "email": "hantoncu@uci.edu", "role": "user"},
    {"first_name": "Jenna", "last_name": "Voutsinas", "email": "jvoutsinas@coh.org", "role": "user"},
    {"first_name": "Jennifer", "last_name": "Benbow", "email": "jbenbow@coh.org", "role": "user"},
    {"first_name": "Jessica", "last_name": "Clague", "email": "jclague@coh.org", "role": "user"},
    {"first_name": "Leslie", "last_name": "Bernstein", "email": "lbernstein@coh.org", "role": "user"},
    {"first_name": "Pamela", "last_name": "Horn-Ross", "email": "pamhornross@gmail.com", "role": "user"},
    {"first_name": "Peggy", "last_name": "Reynolds", "email": "peggy.reynolds@ucsf.edu", "role": "user"},
    {"first_name": "Sophia", "last_name": "Wang", "email": "sowang@coh.org", "role": "user"},
    {"first_name": "Susan", "last_name": "Hurley", "email": "susan.hurley@cpic.org", "role": "user"},
    {"first_name": "Susan", "last_name": "Neuhausen", "email": "sneuhausen@coh.org", "role": "user"},
    {"first_name": "Tina", "last_name": "Clarke", "email": "tina@cpic.org", "role": "user"},
    {"first_name": "Xinxin", "last_name": "Xu", "email": "xinxu@coh.org", "role": "user"},
    {"first_name": "Debbie", "last_name": "Goldberg", "email": "debbie.goldberg@ucsf.edu", "role": "user"},
    {"first_name": "Julie", "last_name": "VonBehren", "email": "julie.vonbehren@ucsf.edu", "role": "user"},
    {"first_name": "Charlie", "last_name": "Zhong", "email": "czhong@coh.org", "role": "user"},
    {"first_name": "Daniel", "last_name": "Quach", "email": "daquach@sdsc.edu", "role": "user"},
    {"first_name": "Brian", "last_name": "Hom", "email": "bhom@ucsd.edu", "role": "user"},
    {"first_name": "Dana", "last_name": "Song", "email": "dana.song4@gmail.com", "role": "user"},
    {"first_name": "Nicholas", "last_name": "Lee", "email": "nxlee@ucsd.edu", "role": "user"},
    {"first_name": "Suzy", "last_name": "Guan", "email": "sguan@ucsd.edu", "role": "user"},
    {"first_name": "June", "last_name": "Park", "email": "jmp008@ucsd.edu", "role": "user"},
    {"first_name": "Victor", "last_name": "Chen", "email": "vic@ucsd.edu", "role": "user"},
    {"first_name": "Arijit", "last_name": "Basu", "email": "arijit.basu@in.ibm.com", "role": "user"},
    {"first_name": "Steven", "last_name": "Blair", "email": "smblair@ucsd.edu", "role": "user"},
    {"first_name": "Anthony", "last_name": "Boyd", "email": "awboyd@sdsc.edu", "role": "user"},
    {"first_name": "Rosemary", "last_name": "Vazquez", "email": "rmvazquez@ucsd.edu", "role": "user"},
    {"first_name": "Eunjung", "last_name": "Lee", "email": "eunjung.lee@med.usc.edu", "role": "user"},
    {"first_name": "Rochelle", "last_name": "Manongdo", "email": "rochellemanongdo@gmail.com", "role": "user"},
    {"first_name": "Anthony", "last_name": "Boyd", "email": "awboyd@sdsc.edu", "role": "user"},
    {"first_name": "Uma", "last_name": "Surapanani", "email": "uma.surapanani@ucop.edu", "role": "user"},
    {"first_name": "Vishal", "last_name": "Singhania", "email": "vissingm@in.ibm.com", "role": "user"},
    {"first_name": "Paul", "last_name": "Hughes", "email": "pahughes@ucsd.edu", "role": "user"},
    {"first_name": "Scott", "last_name": "Grzybowski", "email": "scottgriz@cloudera.com", "role": "user"},
    {"first_name": "Sameer", "last_name": "Karki", "email": "sameer.karki@ucop.edu", "role": "user"},
    {"first_name": "Scott", "last_name": "Grzybowski", "email": "scottgriz@cloudera.com", "role": "user"},
    {"first_name": "John", "last_name": "Sarantakis", "email": "john.sarantakis@ucop.edu", "role": "user"},
    {"first_name": "Rohit", "last_name": "Kumar", "email": "Rohit.Kumar@ucop.edu", "role": "user"},
    {"first_name": "Steven", "last_name": "Blair", "email": "smblair@sdsc.edu", "role": "user"},
    {"first_name": "Anthony", "last_name": "Boyd", "email": "awboyd@sdsc.edu", "role": "user"},
    {"first_name": "Alissa", "last_name": "Mamon", "email": "amamon@ucsd.edu", "role": "user"},
    {"first_name": "Alissa", "last_name": "Mamon", "email": "amamon@sdsc.edu", "role": "user"},
    {"first_name": "Uma", "last_name": "Surapanani", "email": "uma.surapanani@ucop.edu", "role": "user"},
    {"first_name": "Elliot", "last_name": "Pfarr", "email": "epfarr@sdsc.edu", "role": "user"},
    {"first_name": "David", "last_name": "Taylor", "email": "dtaylor@eksh.com", "role": "user"},
    {"first_name": "Joe", "last_name": "Wheeler", "email": "jwheeler@eksh.com", "role": "user"},
    {"first_name": "Chris", "last_name": "Buol", "email": "cboul@eksh.com", "role": "user"},
    {"first_name": "Justin", "last_name": "Lowe", "email": "jlowe@eksh.com", "role": "user"},
    {"first_name": "Alissa", "last_name": "Mamon", "email": "amamon@sdsc.edu", "role": "user"},
    {"first_name": "Jittima", "last_name": "Swasdio", "email": "jittima.swasdio@ucop.edu", "role": "user"},
    {"first_name": "Steve", "last_name": "Hackbarth", "email": "shackbarth@ursahealth.com", "role": "user"},
    {"first_name": "Aaron", "last_name": "Sullivan", "email": "asullivan@ursahealth.com", "role": "user"},
    {"first_name": "Andy", "last_name": "Hackbarth", "email": "ahackbarth@ursahealth.com", "role": "user"},
    {"first_name": "Susan", "last_name": "Whitney", "email": "susan.whitney@ucop.edu", "role": "user"},
    {"first_name": "Joe", "last_name": "Wheeler", "email": "jwheeler@eksh.com", "role": "user"},
    {"first_name": "Adam", "last_name": "Cerullo", "email": "acerullo@eksh.com", "role": "user"},
    {"first_name": "Rohit", "last_name": "Kumar", "email": "rohit.kumar@ucop.edu", "role": "user"},
    {"first_name": "Ahmed", "last_name": "Mustakim", "email": "ahmed.mustakim@ucop.edu", "role": "user"},
    {"first_name": "Paul", "last_name": "Norton", "email": "panorton@sdsc.edu", "role": "user"},
    {"first_name": "Rosemary", "last_name": "Chengson", "email": "Rosemary.Chengson@ucop.edu", "role": "user"},
    {"first_name": "Hooman", "last_name": "Pejman", "email": "Hooman.Pejman@ucop.edu", "role": "user"},
    {"first_name": "Hooman", "last_name": "Pejman", "email": "Hooman.Pejman@ucop.edu", "role": "user"},
    {"first_name": "Hooman", "last_name": "Pejman", "email": "Hooman.Pejman@ucop.edu", "role": "user"},
    {"first_name": "Paul", "last_name": "Norton", "email": "panorton@sdsc.edu", "role": "user"},
    {"first_name": "Taufiqui", "last_name": "Islam", "email": "t7islam@sdsc.edu", "role": "user"},
    {"first_name": "Alissa", "last_name": "Mamon", "email": "amamon@ucsd.edu", "role": "user"},
    {"first_name": "Alissa", "last_name": "Mamon", "email": "amamon@ucsd.edu", "role": "user"},
    {"first_name": "Alissa", "last_name": "Mamon", "email": "amamon@ucsd.edu", "role": "user"},
    {"first_name": "Jess", "last_name": "Lella", "email": "jlella@tableau.com", "role": "user"},
    {"first_name": "Taufiqul", "last_name": "Islam", "email": "t7islam@ucsd.edu", "role": "user"},
    {"first_name": "Taufiqul", "last_name": "Islam", "email": "t7islam@ucsd.edu", "role": "user"},
    {"first_name": "Taufiqul", "last_name": "Islam", "email": "t7islam@ucsd.edu", "role": "user"},
    {"first_name": "Hima", "last_name": "Patlolla", "email": "Hima.Patlolla@ucop.edu", "role": "user"},
    {"first_name": "Taufiq", "last_name": "Islam", "email": "t7islam@sdsc.edu", "role": "user"},
    {"first_name": "Paul", "last_name": "Norton", "email": "panorton@sdsc.edu", "role": "user"},
    {"first_name": "Saran", "last_name": "Reddy", "email": "sar070@sdsc.edu", "role": "user"},
    {"first_name": "Laura", "last_name": "Zaruchaeva", "email": "laura.zaruchaeva@ucop.edu", "role": "user"},
    {"first_name": "Prasad", "last_name": "Govekar", "email": "prasad.govekar@ucop.edu", "role": "user"},
    {"first_name": "Rosemary", "last_name": "Test", "email": "rmvazquez@ucsd.edu", "role": "user"},
    {"first_name": "Saran", "last_name": "Reddy", "email": "sar070@ucsd.edu", "role": "user"},
    {"first_name": "Elliot", "last_name": "Pfarr", "email": "epfarr@sdsc.edu", "role": "user"},
    {"first_name": "Gopinath", "last_name": "Venkatesan", "email": "gopinath.venkatesan@ucop.edu", "role": "user"},
    {"first_name": "Steven", "last_name": "Blair", "email": "smblair@sdsc.edu", "role": "user"},
    {"first_name": "Emily", "last_name": "Weaver", "email": "emily.weaver@ucop.edu", "role": "user"},
    {"first_name": "Indresh", "last_name": "Singh", "email": "isingh@jcvi.org", "role": "user"},
    {"first_name": "Mehmet", "last_name": "Kuscuoglu", "email": "mkuscuog@jcvi.org", "role": "user"},
    {"first_name": "Jiue", "last_name": "Yang", "email": "jayyang@eng.ucsd.edu", "role": "user"},
    {"first_name": "Hima", "last_name": "Patlolla", "email": "Hima.Patlolla@ucop.edu", "role": "user"},
    {"first_name": "Steven", "last_name": "Hunter", "email": "steven.hunter@ucop.edu", "role": "user"},
    {"first_name": "Vijay", "last_name": "Alluri", "email": "vijay.alluri@ucop.edu", "role": "user"},
    {"first_name": "Hooman", "last_name": "Pejman", "email": "Hooman,Pejman@ucop.edu", "role": "user"},
    {"first_name": "Susan", "last_name": "Whitney", "email": "susan.whitney@ucop.edu", "role": "user"},
    {"first_name": "Hima", "last_name": "Patlolla", "email": "hima.patlolla@ucop.edu", "role": "user"},
    {"first_name": "Donna", "last_name": "Carrasco", "email": "dkcarrasco@ucdavis.edu", "role": "user"},
    {"first_name": "Tom", "last_name": "Patterson", "email": "tdpatterson@ucdavis.edu", "role": "user"},
    {"first_name": "Mayra", "last_name": "Davila-Singh", "email": "mdavila@ucdavis.edu", "role": "user"},
    {"first_name": "Tram", "last_name": "Lam", "email": "lamt@mail.nig.gov", "role": "user"},
    {"first_name": "Michelle", "last_name": "Dich", "email": "mdich@coh.org", "role": "user"},
    {"first_name": "Eliza", "last_name": "Miller", "email": "ecm2137@cumc.columbia.edu", "role": "user"},
    {"first_name": "Joshua", "last_name": "Willey", "email": "jzw2@cumc.columbia.edu", "role": "user"},
    {"first_name": "Ying", "last_name": "Kuen Cheung", "email": "yc632@cumc.columbia.edu", "role": "user"},
    {"first_name": "Moon", "last_name": "Park", "email": "ypm2102@cumc.columbia.edu", "role": "user"},
    {"first_name": "Andy", "last_name": "Hathbarth", "email": "ahackbarth@ursahealth.com", "role": "user"},
    {"first_name": "Steve", "last_name": "Hackbarth", "email": "shackbarth@ursahealth.com", "role": "user"},
    {"first_name": "Aaron", "last_name": "Sullivan", "email": "asullivan@ursahealth.com", "role": "user"},
    {"first_name": "Robin", "last_name": "Clarke", "email": "rclark@ursahealth.com", "role": "user"},
    {"first_name": "George", "last_name": "Louie", "email": "george.louie@ucop.edu", "role": "user"},
    {"first_name": "Indresh", "last_name": "Singh", "email": "isingh@jcvi.org", "role": "user"},
    {"first_name": "Anyi", "last_name": "Zheng", "email": "anyi.zheng@ucop.edu", "role": "user"},
    {"first_name": "Lynn", "last_name": "Nguyen", "email": "ltn066@ucsd.edu", "role": "user"},
    {"first_name": "Vianey", "last_name": "Perez", "email": "vperezma@ucsd.edu", "role": "user"},
    {"first_name": "Renu", "last_name": "Bansal", "email": "rebansal@ucsd.edu", "role": "user"},
    {"first_name": "Steve", "last_name": "Hunter", "email": "Steven.Hunter@ucsd.edu", "role": "user"},
    {"first_name": "Jennifer", "last_name": "Kramer", "email": "jkramer@ucsd.edu", "role": "user"},
    {"first_name": "Tim", "last_name": "Morse", "email": "tmorse@ucsd.edu", "role": "user"},
    {"first_name": "Douglas", "last_name": "Shieh", "email": "sshieh@ucsd.edu", "role": "user"},
    {"first_name": "Jenny", "last_name": "Chang", "email": "jjchang@uci.edu", "role": "user"},
    {"first_name": "Nicole", "last_name": "Delgado", "email": "nicdelgado@coh.org", "role": "user"},
    {"first_name": "Ed", "last_name": "Test", "email": "ewade@sdsc.edu", "role": "user"},
    {"first_name": "Richard", "last_name": "Scheuermann", "email": "rscheuermann@jcvi.org", "role": "user"},
    {"first_name": "Max", "last_name": "Qian", "email": "mqian@jcvi.org", "role": "user"},
    {"first_name": "Lucy", "last_name": "Stewart", "email": "lstewart@jcvi.org", "role": "user"},
    {"first_name": "Brett", "last_name": "Pickett", "email": "bpickett@jcvi.org", "role": "user"},
    {"first_name": "Robert", "last_name": "Sinkovits", "email": "sinkovit@sdsc.edu", "role": "user"},
    {"first_name": "Andreas", "last_name": "Goetz", "email": "agoetz@sdsc.org", "role": "user"},
    {"first_name": "Madhusudan", "last_name": "Gujral", "email": "mgujral@ucsd.edu", "role": "user"},
    {"first_name": "James", "last_name": "Crowe", "email": "james.crowe@vanderbilt.edu", "role": "user"},
    {"first_name": "Cinque", "last_name": "Soto", "email": "cinque.soto@vanderbilt.edu", "role": "user"},
    {"first_name": "Robin", "last_name": "Bombardi", "email": "bombarrg@vvcenter.org", "role": "user"},
    {
        "first_name": "Andre",
        "last_name": "Branchizio",
        "email": "andre.j.branchizio@vanderbilt.edu",
        "role": "user"
    },
    {
        "first_name": "Andrea",
        "last_name": "Pruijssers",
        "email": "ardina.pruijssers@vanderbilt.edu",
        "role": "user"
    },
    {"first_name": "Tobias", "last_name": "Kollmann", "email": "tkollm@mac.com", "role": "user"},
    {"first_name": "Manish", "last_name": "Sadarangani", "email": "msadarangani@bcchr.ubc.ca", "role": "user"},
    {"first_name": "Rym Ben Othman", "last_name": "Aniba", "email": "rbenothman@bcchr.ubc.ca", "role": "user"},
    {"first_name": "Kim", "last_name": "Marty", "email": "kmarty@bcchr.ubc.ca", "role": "user"},
    {"first_name": "Wayne", "last_name": "Koff", "email": "wkoff@humanvaccinesproject.org", "role": "user"},
    {
        "first_name": "Ted",
        "last_name": "Schenkelberg",
        "email": "tschenkelberg@humanvaccinesproject.org",
        "role": "user"
    },
    {"first_name": "Surendra", "last_name": "Gade", "email": "surendra.gade@kwartile.com", "role": "user"},
    {"first_name": "Swapnil", "last_name": "Kamble", "email": "669-258-9653", "role": "user"},
    {"first_name": "Vinay", "last_name": "Joshi", "email": "vinay.joshi@kwartile.com", "role": "user"},
    {"first_name": "Paul", "last_name": "Norton", "email": "panorton@ucsd.edu", "role": "user"},
    {"first_name": "Paul", "last_name": "Norton", "email": "panorton@ucsd.edu", "role": "user"},
    {"first_name": "Paul", "last_name": "Norton", "email": "panorton@ucsd.edu", "role": "user"},
    {"first_name": "Emma", "last_name": "Spielfogel", "email": "espielfogel@coh.org", "role": "user"},
    {"first_name": "Colin", "last_name": "Beam", "email": "cbeam@ursahealth.com", "role": "user"},
    {"first_name": "Vinay", "last_name": "Joshi", "email": "vinay.joshi@kwartile.com", "role": "user"},
    {"first_name": "Surendra", "last_name": "Gade", "email": "surendra.gade@kwartile.com", "role": "user"},
    {"first_name": "Satish", "last_name": "Pasupuleti", "email": "satish.pasupuleti@ucop.edu", "role": "user"},
    {"first_name": "Federick", "last_name": "Kehret", "email": "rick.kehret@ucop.edu", "role": "user"},
    {"first_name": "April", "last_name": "Kinninger", "email": "kinninge@usc.edu", "role": "user"},
    {"first_name": "Nick", "last_name": "Naughton", "email": "nnaughto@usc.edu", "role": "user"},
    {"first_name": "Mehmet", "last_name": "Kuscuoglu", "email": "mkuscuog@jcvi.org", "role": "user"},
    {"first_name": "Craig", "last_name": "McBurnett", "email": "cmcburnett@lumecloud.com", "role": "user"},
    {"first_name": "Tanner", "last_name": "Knight", "email": "tanner@mysolidbox.com", "role": "user"},
    {"first_name": "Phillip", "last_name": "Lewis", "email": "phillip.lewis@Epigrid.com", "role": "user"},
    {"first_name": "Andrea", "last_name": "Skiera", "email": "alskiera@ucdavis.edu", "role": "user"},
    {"first_name": "Kumi", "last_name": "Chinen", "email": "kchinen@ucdavis.edu", "role": "user"},
    {
        "first_name": "Brenda",
        "last_name": "Birmann",
        "email": "brenda.birmann@channing.harvard.edu",
        "role": "user"
    },
    {"first_name": "Ke", "last_name": "Wang", "email": "nhkew@channing.harvard.edu", "role": "user"},
    {"first_name": "Robert", "last_name": "Mowers", "email": "rmmowers@ucdavis.edu", "role": "user"},
    {"first_name": "Gina", "last_name": "Intinarelli", "email": "gina.intinarelli@ucsf.edu", "role": "user"},
    {"first_name": "Alma", "last_name": "Hernandez", "email": "alma.hernandez@medsch.ucr.edu", "role": "user"},
    {"first_name": "Keila", "last_name": "Galvan", "email": "keila.galvan@ucsf.edu", "role": "user"},
    {"first_name": "Gary", "last_name": "Hagney", "email": "ghagney@ucsd.edu", "role": "user"},
    {"first_name": "Marilyn", "last_name": "Stebbins", "email": "marily.stebbins@ucsf.edu", "role": "user"},
    {"first_name": "Lily", "last_name": "Roh", "email": "lroh@mednet.ucla.edu", "role": "user"},
    {"first_name": "Melanie", "last_name": "Joe", "email": "mdjoe@uci.edu", "role": "user"},
    {"first_name": "Bruce", "last_name": "Ball", "email": "bball@uci.edu", "role": "user"},
    {"first_name": "Kathryn", "last_name": "Medders", "email": "kmedders@ucsd.edu", "role": "user"},
    {"first_name": "Naveen", "last_name": "Raja", "email": "rgupta@mednet.ucla.edu", "role": "user"},
    {"first_name": "Reshma", "last_name": "Gupta", "email": "rgupta@mednet.ucla.edu", "role": "user"},
    {"first_name": "Lisa", "last_name": "Kroon", "email": "lisa.kroon@ucsf.edu", "role": "user"},
    {"first_name": "Mary", "last_name": "McGinty", "email": "mary.mcginty@ucsf.edu", "role": "user"},
    {"first_name": "Tae", "last_name": "Kim", "email": "taekyu.kim@medsch.ucr.edu", "role": "user"},
    {"first_name": "Rebecca", "last_name": "Pace", "email": "rpace@mednet.ucla.edu", "role": "user"},
    {"first_name": "Todd", "last_name": "Moody", "email": "tmoody@eksh.com", "role": "user"},
    {"first_name": "Hariprasad", "last_name": "Madas", "email": "hariprasad.madras@ucop.edu", "role": "user"},
    {"first_name": "Sabrina", "last_name": "Shiroma", "email": "sshiroma@ucsd.edu", "role": "user"},
    {"first_name": "Weija", "last_name": "Qian", "email": "weqian@ucsd.edu", "role": "user"},
    {"first_name": "Lauren", "last_name": "Collin", "email": "lcollin@ucsd.edu", "role": "user"},
    {"first_name": "Karla", "last_name": "Holmberg", "email": "cpssupport@ucop.edu", "role": "user"},
    {"first_name": "Indresh", "last_name": "Singh", "email": "isingh@jcvi.org", "role": "user"},
    {"first_name": "Mark", "last_name": "Otero", "email": "motero@ucsd.edu", "role": "user"},
    {"first_name": "Irina", "last_name": "Tsimring", "email": "itsimring@ucsd.edu", "role": "user"},
    {"first_name": "Eric", "last_name": "Gallimore", "email": "egallimore@ucsd.edu", "role": "user"},
    {"first_name": "Lisa", "last_name": "Hazard", "email": "lhazard@ucsd.edu", "role": "user"},
    {"first_name": "Robert ", "last_name": "Hess", "email": "rfhess@ucsd.edu", "role": "user"},
    {"first_name": "J. Shannon", "last_name": "Scott", "email": "jsscott@ucsd.edu", "role": "user"},
    {"first_name": "Daniel", "last_name": "Bedenko", "email": "dbedenko@ucsd.edu", "role": "user"},
    {"first_name": "Joel", "last_name": "Hazard", "email": "jhazard@ucsd.edu", "role": "user"},
    {"first_name": "Scott", "last_name": "Katz", "email": "sdkatz@ucsd.edu", "role": "user"},
    {"first_name": "Andrew ", "last_name": "Nager", "email": "anager@ucsd.edu", "role": "user"},
    {"first_name": "Eric", "last_name": "Terrill", "email": "eterill@ucsd.edu", "role": "user"},
    {"first_name": "Caroline", "last_name": "Taylor", "email": "caroline.taylor@vumc.org", "role": "user"},
    {"first_name": "Abel", "last_name": "Lin", "email": "Abel_Lin@nihonkohden.com", "role": "user"},
    {"first_name": "Hamdi", "last_name": "Abdi", "email": "hamdi.abdi@nih.gov", "role": "user"},
    {"first_name": "Kirstin", "last_name": "Pirie", "email": "kirstin.pirie@ndph.ox.ac.uk", "role": "user"},
    {"first_name": "Ankita", "last_name": "Mahanta", "email": "amahanta@in.ibm.com", "role": "user"},
    {"first_name": "Shanthi", "last_name": "Doddi", "email": "shanti.doddi@kwartile.com", "role": "user"},
    {"first_name": "Sandra", "last_name": "Huffman", "email": "shuffman@coh.org", "role": "user"},
    {"first_name": "Joy", "last_name": "Smith", "email": "joy.smith@ucop.edu", "role": "user"},
    {"first_name": "Rahul", "last_name": "Chawla", "email": "rahul.chawla@ucop.edu", "role": "user"},
    {"first_name": "Tarun", "last_name": "Arora", "email": "tarun.arora@ucop.edu", "role": "user"},
    {"first_name": "Rahul", "last_name": "Chawla", "email": "Rahul.Chawla@ucop.edu", "role": "user"},
    {"first_name": "Rahul", "last_name": "Chawla", "email": "Rahul.Chawla@ucop.edu", "role": "user"},
    {"first_name": "Satish", "last_name": "Pasupuleti", "email": "satish.pasupuleti@ucop.edu", "role": "user"},
    {"first_name": "Emily", "last_name": "Weaver", "email": "Emily.Weaver@ucop.edu", "role": "user"},
    {"first_name": "Emily", "last_name": "Weaver", "email": "Emily.Weaver@ucop.edu", "role": "user"},
    {"first_name": "Emily", "last_name": "Weaver", "email": "Emily.Weaver@ucop.edu", "role": "user"},
    {"first_name": "Emily", "last_name": "Weaver", "email": "Emily.Weaver@ucop.edu", "role": "user"},
    {"first_name": "Rahul", "last_name": "Chawla", "email": "Rahul.Chawla@ucop.edu", "role": "user"},
    {"first_name": "Tarun", "last_name": "Arora", "email": "Tarun.Arora@ucop.edu", "role": "user"},
    {"first_name": "Lorena", "last_name": "Pacheco", "email": "l2pachec@ucsd.edu", "role": "user"},
    {"first_name": "Mihee", "last_name": "Lee", "email": "ml_322@usc.edu", "role": "user"},
    {"first_name": "Dave", "last_name": "Ensberg", "email": "densberg@ucsd.edu", "role": "user"},
    {"first_name": "William", "last_name": "Hodgkiss", "email": "whodgkiss@ucsd.edu", "role": "user"},
    {"first_name": "Emily", "last_name": "Weaver", "email": "Emily.Weaver@ucop.edu", "role": "user"},
    {"first_name": "Melanie", "last_name": "Lopez", "email": "mmlopez2@sdsc.edu", "role": "user"},
    {"first_name": "Ashley", "last_name": "Amaladhas", "email": "aamaladh@ucsd.edu", "role": "user"},
    {"first_name": "Edgar", "last_name": "Gomez", "email": "gomez.edgar1558@gmail.com", "role": "user"},
    {"first_name": "S. Lani", "last_name": "Park", "email": "sungship@med.usc.edu", "role": "user"},
    {"first_name": "Yaa", "last_name": "Klu", "email": "ykk2116@cumc.columbia.edu", "role": "user"},
    {"first_name": "Natalie", "last_name": "Bello", "email": "nb338@columbia.edu", "role": "user"},
    {"first_name": "Ann", "last_name": "Hamilton", "email": "ahamilt@med.usc.edu", "role": "user"},
    {"first_name": "Eva", "last_name": "Goode", "email": "Eva.Goode@ucop.edu", "role": "user"},
    {"first_name": "Kristen", "last_name": "Neal", "email": "Kristen.Neal@ucop.edu", "role": "user"},
    {"first_name": "Abhishek", "last_name": "Ailneni", "email": "abhishek.ailneni@ucop.edu", "role": "user"},
    {"first_name": "Gopinath", "last_name": "Venkatesan", "email": "Gopinath.Venkatesan@ucop.edu", "role": "user"},
    {"first_name": "Vijay", "last_name": "Alluri", "email": "Vijay.Alluri@ucop.edu", "role": "user"},
    {"first_name": "Jittima", "last_name": "Swasdio", "email": "Jittima.Swasdio@ucop.edu", "role": "user"},
    {"first_name": "Ahmed", "last_name": "Mustakim", "email": "Ahmed.Mustakim@ucop.edu", "role": "user"},
    {"first_name": "Lennie", "last_name": "Wong", "email": "LennieWong@coh.org", "role": "user"},
    {"first_name": "Tiffany", "last_name": "Sanchez", "email": "trs21111@cumc.columbia.edu", "role": "user"},
    {"first_name": "Minju", "last_name": "Kim", "email": "mjk081@ucsd.edu", "role": "user"},
    {"first_name": "Jittima", "last_name": "Swasdio", "email": "Jittima.Swasdio@ucop.edu", "role": "user"},
    {"first_name": "Ahmed", "last_name": "Mustakim", "email": "Ahmed.Mustakim@ucop.edu", "role": "user"},
    {"first_name": "Robert", "last_name": "Bjornson", "email": "robert.bjornson@yale.edu", "role": "user"},
    {"first_name": "Jason", "last_name": "Ignatius", "email": "jason.ignatius@yale.edu", "role": "user"},
    {"first_name": "Jiue-An", "last_name": "Yang", "email": "jayyang@eng.ucsd.edu", "role": "user"},
    {"first_name": "Bhaskar", "last_name": "Gudimetla", "email": "bhaskar.gudimetla@kwartile.com", "role": "user"},
    {"first_name": "Arthur", "last_name": "Webb", "email": "arthur_webb2@nihonkohden.com", "role": "user"},
    {"first_name": "Alissa", "last_name": "Mamon", "email": "amamon@sdsc.edu", "role": "user"},
    {"first_name": "Maggie", "last_name": "Li", "email": "maggieli01u@berkeley.edu", "role": "user"},
    {"first_name": "Hengrui", "last_name": "Hu", "email": "hhu@coh.org", "role": "user"},
    {"first_name": "Winston", "last_name": "Armstrong", "email": "warmstrong@sdsc.edu", "role": "user"},
    {"first_name": "Emily", "last_name": "Weaver", "email": "Emily.Weaver-ucop.edu@ucop.edu", "role": "user"},
    {"first_name": "Hooman", "last_name": "Pejman", "email": "Hooman.Pejman-ucop.edu@ucop.edu", "role": "user"},
    {
        "first_name": "Satish",
        "last_name": "Pasupuleti",
        "email": "Satish.Pasupuleti-ucop.edu@ucop.edu",
        "role": "user"
    },
    {"first_name": "Susan", "last_name": "Whitney", "email": "Susan.Whitney-ucop.edu@ucop.edu", "role": "user"},
    {"first_name": "Vijay", "last_name": "Alluri", "email": "Vijay.Alluri-ucop.edu@ucop.edu", "role": "user"},
    {"first_name": "Kai", "last_name": "Lin", "email": "klin@sdsc.edu", "role": "user"},
    {"first_name": "Creat", "last_name": "Tsou", "email": "mtsou@sdsu.edu", "role": "user"},
    {"first_name": "Yulu", "last_name": "Chen", "email": "ychen2793@sdsc.edu", "role": "user"},
    {"first_name": "Leena", "last_name": "Patil", "email": "leena.patil@kwartile.com", "role": "user"},
    {"first_name": "Jian", "last_name": "Shen", "email": "jis025@ucsd.edu", "role": "user"},
    {"first_name": "Chris", "last_name": "Salazar", "email": "chris_salazar@uri.edu", "role": "user"},
    {"first_name": "Carlos", "last_name": "Javier", "email": "carlos_javier@my.uri.edu", "role": "user"},
    {"first_name": "Arun", "last_name": "Shukla", "email": "shuklaa@uri.edu", "role": "user"},
    {"first_name": "Alfred", "last_name": "Speredelozzi", "email": "alfredjr@uri.edu", "role": "user"},
    {"first_name": "Kai", "last_name": "Gemba", "email": "kgemba@ucsd.edu", "role": "user"},
    {"first_name": "Mary", "last_name": "Meyer", "email": "Mary.Meyer@ucop.edu", "role": "user"},
    {"first_name": "Haihong", "last_name": "Huang", "email": "hhuang4@sdsu.edu", "role": "user"},
    {"first_name": "Krishna", "last_name": "Mohan", "email": "Krishna.Mohan-ucop.edu@ucop.edu", "role": "user"},
    {"first_name": "Timothy", "last_name": "Ruchti", "email": "Timothy_Ruchti@nihonkohden.com", "role": "user"},
    {"first_name": "Elisa", "last_name": "Tang", "email": "Elisa.Tang@ucop.edu", "role": "user"},
    {"first_name": "John", "last_name": "Nuthalapaty", "email": "john.nuthalapaty@ucop.edu", "role": "user"},
    {"first_name": "Julie", "last_name": "Hernandez", "email": "julieah1@uci.edu", "role": "user"},
    {"first_name": "Linda", "last_name": "Gonzalez", "email": "lindagonzalez@ucla.edu", "role": "user"},
    {"first_name": "Tami", "last_name": "Mays", "email": "tamays@ucdavis.edu", "role": "user"},
    {"first_name": "Lawrence", "last_name": "Kushi", "email": "larry.kushi@kp.org", "role": "user"},
    {"first_name": "Shelley", "last_name": "Tworoger", "email": "shelley.tworoger@moffitt.org", "role": "user"},
    {"first_name": "Rocco", "last_name": "Landi", "email": "rocco.landi@childrens.harvard.edu", "role": "user"},
    {"first_name": "Vikram", "last_name": "Haridass", "email": "vharidas@uci.edu", "role": "user"},
    {"first_name": "Ayesha", "last_name": "Sherzai", "email": "asherzai@llu.edu", "role": "user"},
    {"first_name": "Humberto", "last_name": "Parada", "email": "hparada@sdsu.edu", "role": "user"},
    {"first_name": "Christina", "last_name": "Slee", "email": "cakuenne@ucdavis.edu", "role": "user"},
    {"first_name": "Kristie", "last_name": "Elton", "email": "Kristie.Elton-ucop.edu@ucop.edu", "role": "user"},
    {"first_name": "Anyi", "last_name": "Zheng", "email": "Anyi.Zheng-ucop.edu@ucop.edu", "role": "user"},
    {"first_name": "Elizabeth", "last_name": "Johnston", "email": "ejmjohns@ucdavis.edu", "role": "user"},
    {"first_name": "Craig", "last_name": "Kitaoka", "email": "Craig.Kitaoka@ucop.edu", "role": "user"},
    {"first_name": "Kenneth", "last_name": "Smith", "email": "ken.smith-ucop.edu@ucop.edu", "role": "user"},
    {"first_name": "Rebecca", "last_name": "Nelson", "email": "rnelson@coh.org", "role": "user"},
    {"first_name": "Kimberly", "last_name": "Sieg", "email": "klsieg@ucdavis.edu", "role": "user"},
    {"first_name": "Melanie", "last_name": "Alexandre", "email": "MMAlexandre@lbl.gov", "role": "user"},
    {"first_name": "Brent", "last_name": "Cooley", "email": "Brent.Cooley-ucop.edu@ucop.edu", "role": "user"},
    {"first_name": "Deitrich", "last_name": "Singletary", "email": "DSingletary@lbl.gov", "role": "user"},
    {"first_name": "Gabriella", "last_name": "Renteria", "email": "ggrenter@ucdavis.edu", "role": "user"},
    {"first_name": "Veronica", "last_name": "Nelson", "email": "Veronica.Nelson-ucop.edu@ucop.edu", "role": "user"},
    {"first_name": "Alyssa", "last_name": "Le", "email": "alyssal@uci.edu", "role": "user"},
    {
        "first_name": "Jason",
        "last_name": "Peterson",
        "email": "046f34a140f559a9014277fd86630b9f@ucsd.edu",
        "role": "user"
    },
    {"first_name": "Joseph", "last_name": "Brothman", "email": "jbrothma@uci.edu", "role": "user"},
    {"first_name": "Matthew", "last_name": "Carlson", "email": "516890@ucsf.edu", "role": "user"},
    {"first_name": "Dorothy", "last_name": "Ong", "email": "dong@uci.edu", "role": "user"},
    {"first_name": "Tricia", "last_name": "Ochoa", "email": "268452@ucsf.edu", "role": "user"},
    {"first_name": "ERIK", "last_name": "Eggins", "email": "eeggins@ucla.edu", "role": "user"},
    {
        "first_name": "Elizabeth",
        "last_name": "Billberry",
        "email": "046f356d40a6d1580140a6d1eccd005f@ucsd.edu",
        "role": "user"
    },
    {"first_name": "Nathaniel", "last_name": "Tabita", "email": "ntabita@uci.edu", "role": "user"},
    {"first_name": "Michael", "last_name": "Lillie", "email": "mlillie@ucdavis.edu", "role": "user"},
    {"first_name": "ADRIENNE", "last_name": "Malka", "email": "lmalka1@ucla.edu", "role": "user"},
    {"first_name": "DIANNA", "last_name": "Cumpian", "email": "dcumpian@ucla.edu", "role": "user"},
    {"first_name": "Judith", "last_name": "Rosen", "email": "770412@ucsf.edu", "role": "user"},
    {"first_name": "Brian", "last_name": "Oatman", "email": "baoatman@ucdavis.edu", "role": "user"},
    {"first_name": "Kaila", "last_name": "Benton-Vitz", "email": "kailabv@ucdavis.edu", "role": "user"},
    {"first_name": "Sandra", "last_name": "Conrrad", "email": "sconrrad@uci.edu", "role": "user"},
    {
        "first_name": "Edith",
        "last_name": "Mitchell",
        "email": "046f34e745e282dd01481e9a416f14b1@ucsd.edu",
        "role": "user"
    },
    {"first_name": "Cynthia", "last_name": "Vazquez", "email": "cmvazquez@ucla.edu", "role": "user"},
    {"first_name": "Julius", "last_name": "Caluag", "email": "caluagj@ucla.edu", "role": "user"},
    {
        "first_name": "Pamela",
        "last_name": "Hauser",
        "email": "046f34cb52e1582f0152f10e3ee70277@ucsd.edu",
        "role": "user"
    },
    {"first_name": "Martha", "last_name": "Nunez-Flores", "email": "mnunezfl@uci.edu", "role": "user"},
    {"first_name": "William", "last_name": "Huey", "email": "wehuey@uci.edu", "role": "user"},
    {"first_name": "Kevin", "last_name": "Confetti", "email": "Kevin.Confetti-ucop.edu@ucop.edu", "role": "user"},
    {"first_name": "Cynthia", "last_name": "Chow", "email": "cchow8679@sdsu.edu", "role": "user"},
    {"first_name": "Rachelle", "last_name": "De Ocampo", "email": "rdeocampo@sdsc.edu", "role": "user"},
    {"first_name": "Wayne", "last_name": "Kepner", "email": "wkepner2437@sdsu.edu", "role": "user"},
    {"first_name": "Inez", "last_name": "Lo Coco", "email": "565012@ucsf.edu", "role": "user"},
    {
        "first_name": "Corey",
        "last_name": "Singleton",
        "email": "046f356d40a6d1580140a6d22fd601a8@ucsd.edu",
        "role": "user"
    },
    {
        "first_name": "Kimberlee",
        "last_name": "Eskierka",
        "email": "046f34e759b4641e0159cc00ff381fe9@ucsd.edu",
        "role": "user"
    },
    {"first_name": "Ariel", "last_name": "Neumann", "email": "aneumann@uri.edu", "role": "user"},
    {"first_name": "David", "last_name": "Grenier", "email": "david_grenier@uri.edu", "role": "user"},
    {"first_name": "Joel", "last_name": "Stewart", "email": "jstewart@uri.edu", "role": "user"},
    {"first_name": "Kim", "last_name": "Pierson", "email": "kim_pierson@uri.edu", "role": "user"},
    {"first_name": "Li", "last_name": "Yuan", "email": "li_yuan@uri.edu", "role": "user"},
    {"first_name": "Megan", "last_name": "Swindal", "email": "mswindal@uri.edu", "role": "user"},
    {"first_name": "Daniel", "last_name": "Miller", "email": "099077@ucsf.edu", "role": "user"},
    {"first_name": "Lisa", "last_name": "Wisser", "email": "lwisser@ucsc.edu", "role": "user"},
    {"first_name": "Arash", "last_name": "Delavar", "email": "adelavar@ucsd.edu", "role": "user"},
    {"first_name": "Jittima", "last_name": "Swasdio", "email": "Jittima.Swasdio-ucop.edu@ucop.edu", "role": "user"},
    {"first_name": "Wanda", "last_name": "Fitzgerald", "email": "WFitzgerald@coh.org", "role": "user"},
    {"first_name": "Cindy", "last_name": "Delgado", "email": "cadelgad@ucsc.edu", "role": "user"},
    {"first_name": "Nini", "last_name": "Furst", "email": "ninif@ucr.edu", "role": "user"},
    {"first_name": "Monica", "last_name": "Dussert", "email": "monica79@ucsb.edu", "role": "user"},
    {"first_name": "Jim", "last_name": "Byrnes", "email": "byrnes@uri.edu", "role": "user"},
    {"first_name": "Mike", "last_name": "Imazumi", "email": "mimazumi@berkeley.edu", "role": "user"},
    {"first_name": "Jessica", "last_name": "DeHart", "email": "jessica.dehart@cgu.edu", "role": "user"},
    {"first_name": "Sandrah", "last_name": "Eckel", "email": "eckel@usc.edu", "role": "user"},
    {"first_name": "Myles", "last_name": "Cockburn", "email": "myles.cockburn@ucdenver.edu", "role": "user"},
    {"first_name": "Patrick", "last_name": "Goff", "email": "ptgoff@berkeley.edu", "role": "user"},
    {"first_name": "Ruby", "last_name": "Antonio", "email": "Ruby.Antonio-ucop.edu@ucop.edu", "role": "user"},
    {"first_name": "Erica", "last_name": "Ambeba", "email": "eambeba@ucsd.edu", "role": "user"},
    {"first_name": "Mark", "last_name": "Freiberg", "email": "996276@ucsf.edu", "role": "user"},
    {
        "first_name": "Amy",
        "last_name": "Schultz",
        "email": "046f34cb54e4aac00155ffb69f3e160f@ucsd.edu",
        "role": "user"
    },
    {"first_name": "Jennifer", "last_name": "Mempin", "email": "jenibear@ucla.edu", "role": "user"},
    {"first_name": "Feng", "last_name": "Liu-Smith", "email": "liufe@gwu.edu", "role": "user"},
    {"first_name": "Emily", "last_name": "Blake", "email": "efblake@gwu.edu", "role": "user"},
    {"first_name": "Merissa", "last_name": "Mayo", "email": "merissa.b.mayo@vumc.org", "role": "user"},
    {"first_name": "Taylor", "last_name": "Jones", "email": "taylor.l.jones@vumc.org", "role": "user"},
    {"first_name": "Megan", "last_name": "Vodzak", "email": "megan.e.vodzak@vumc.org", "role": "user"},
    {
        "first_name": "Rowena",
        "last_name": "Cadacio",
        "email": "046f34e64885fc9001488e8249c90023@ucsd.edu",
        "role": "user"
    },
    {"first_name": "Mal", "last_name": "Donohue", "email": "mdonohue@ucmerced.edu", "role": "user"},
    {"first_name": "Diane", "last_name": "Evans", "email": "devans@ihpaco.org", "role": "user"},
    {"first_name": "Melanie", "last_name": "Bowdish", "email": "melanie_bowdish@uri.edu", "role": "user"},
    {"first_name": "Vikram", "last_name": "Test", "email": "vharidas@uci.edu", "role": "user"},
    {"first_name": "Purva", "last_name": "Jain", "email": "puj001@ucsd.edu", "role": "user"},
    {"first_name": "Caihong", "last_name": "Xia", "email": "caihongx@usc.edu", "role": "user"},
    {"first_name": "Huiyu", "last_name": "Deng", "email": "huiyuden@usc.edu", "role": "user"},
    {"first_name": "Lihua", "last_name": "Liu", "email": "lihualiu@usc.edu", "role": "user"},
    {"first_name": "Hamid", "last_name": "Fonooni", "email": "hfonooni@ucdavis.edu", "role": "user"},
    {
        "first_name": "Justin",
        "last_name": "Turner",
        "email": "2c9034e636ae3021013911aa7a0626dc@ucsd.edu",
        "role": "user"
    },
    {"first_name": "Rahul", "last_name": "Chawla", "email": "Rahul.Chawla-ucop.edu@ucop.edu", "role": "user"},
    {"first_name": "Michelle", "last_name": "Amante", "email": "mamantei@ucla.edu", "role": "user"},
    {"first_name": "Yvonne", "last_name": "Ybarra", "email": "ybarray@uci.edu", "role": "user"},
    {"first_name": "Ibiyemi", "last_name": "Olowoyeye", "email": "yemi@ucdavis.edu", "role": "user"},
    {"first_name": "Allison", "last_name": "Akbaroff", "email": "aakbaroff@ucla.edu", "role": "user"},
    {"first_name": "Jill", "last_name": "Evans-Grinbergs", "email": "jevansgr@ucdavis.edu", "role": "user"},
    {"first_name": "Rebecca", "last_name": "Hariri", "email": "193249@ucsf.edu", "role": "user"},
    {"first_name": "Carrie", "last_name": "Frandsen", "email": "Carrie.Frandsen-ucop.edu@ucop.edu", "role": "user"},
    {"first_name": "Donald", "last_name": "Van Wie", "email": "585896@ucsf.edu", "role": "user"},
    {"first_name": "Jay", "last_name": "Lomeli", "email": "jlomeli3@ucmerced.edu", "role": "user"},
    {"first_name": "Tracy", "last_name": "Stark", "email": "tstark@ucr.edu", "role": "user"},
    {"first_name": "Vanessa", "last_name": "Curtis", "email": "430252@ucsf.edu", "role": "user"},
    {
        "first_name": "Kriston",
        "last_name": "Morris",
        "email": "046f34a23e097cbe0140085cabc91495@ucsd.edu",
        "role": "user"
    },
    {
        "first_name": "Marcia",
        "last_name": "Isakari",
        "email": "046f34cb4b34a7cf014b4c32bf9103dc@ucsd.edu",
        "role": "user"
    },
    {"first_name": "Stephanie", "last_name": "Ngan", "email": "sngan@berkeley.edu", "role": "user"},
    {"first_name": "Tushondra", "last_name": "Thomas", "email": "tuthomas@coh.org", "role": "user"},
    {"first_name": "Sabrina", "last_name": "Welsh", "email": "swelsh@humanvaccinesproject.org", "role": "user"},
    {"first_name": "Carolyn", "last_name": "Moderbacher", "email": "cmoderbacher@lji.org", "role": "user"},
    {"first_name": "Kristen", "last_name": "Anderson", "email": "kristena@ucdavis.edu", "role": "user"},
    {"first_name": "Phyllis", "last_name": "Simmons", "email": "293624@ucsf.edu", "role": "user"},
    {
        "first_name": "Tammie",
        "last_name": "Haugen",
        "email": "046f34e75dbf4f8a015e80ea6f1707cd@ucsd.edu",
        "role": "user"
    },
    {"first_name": "Ingrid", "last_name": "Fahr", "email": "ingridf@ucr.edu", "role": "user"},
    {"first_name": "David", "last_name": "Martino", "email": "David.Martino@telethonkids.org.au", "role": "user"},
    {"first_name": "Amy", "last_name": "Lee", "email": "amy.lee@ubc.ca", "role": "user"},
    {"first_name": "Travis", "last_name": "Blimkie", "email": "travis@hancocklab.com", "role": "user"},
    {"first_name": "David", "last_name": "Schibli", "email": "dschibli@proteincentre.com", "role": "user"},
    {"first_name": "Yassene", "last_name": "Mohammed", "email": "Yassene@proteincentre.com", "role": "user"},
    {"first_name": "Derek", "last_name": "Smith", "email": "derek@proteincentre.com", "role": "user"},
    {"first_name": "Pakito", "last_name": "Martinez", "email": "fmartinez@metabolon.com", "role": "user"},
    {"first_name": "Timo", "last_name": "Lassmann", "email": "timo.lassmann@telethonkids.org.au", "role": "user"},
    {
        "first_name": "Denise",
        "last_name": "Devall",
        "email": "046f34e65dbf22f6015e0adfb8da02d6@ucsd.edu",
        "role": "user"
    },
    {"first_name": "Sheila", "last_name": "Hedayati", "email": "shedayat@ucr.edu", "role": "user"},
    {"first_name": "Brian", "last_name": "Macdonald", "email": "bmacdon1@ucsc.edu", "role": "user"},
    {"first_name": "Kristin", "last_name": "Amlie", "email": "072760@ucsf.edu", "role": "user"},
    {"first_name": "Alexandra", "last_name": "Norris", "email": "ajnorris@ucla.edu", "role": "user"},
    {"first_name": "Justin", "last_name": "Sabo", "email": "jsabo@ucla.edu", "role": "user"},
    {"first_name": "Erika", "last_name": "Schwilk", "email": "schwilk@berkeley.edu", "role": "user"},
    {"first_name": "Monique", "last_name": "Lapalm", "email": "moniquelapalm@ucla.edu", "role": "user"},
    {"first_name": "Patricia", "last_name": "Bertlow", "email": "701378@ucsf.edu", "role": "user"},
    {"first_name": "Randolph", "last_name": "Sauser", "email": "rsauser@ucla.edu", "role": "user"},
    {"first_name": "Yensen", "last_name": "Lin", "email": "yensen125@ucla.edu", "role": "user"},
    {"first_name": "Clyde", "last_name": "Blackwelder", "email": "clydebl@ucr.edu", "role": "user"},
    {"first_name": "Natalie", "last_name": "Jimenez", "email": "natalia.jimenez@vumc.org", "role": "user"},
    {"first_name": "Sandra", "last_name": "Yoder", "email": "sandra.yoder@vumc.org", "role": "user"},
    {"first_name": "Buddy", "last_name": "Creech", "email": "buddy.creech@vumc.org", "role": "user"},
    {"first_name": "Amit", "last_name": "Singh", "email": "amit_s@berkeley.edu", "role": "user"},
    {"first_name": "Roy", "last_name": "Berke", "email": "rberke@berkeley.edu", "role": "user"},
    {"first_name": "Virginia", "last_name": "Thomas", "email": "virginia@ucsb.edu", "role": "user"},
    {"first_name": "Lulu", "last_name": "Song", "email": "lulusong@usc.edu", "role": "user"},
    {"first_name": "Charleen", "last_name": "Adams", "email": "chaadams@coh.org", "role": "user"},
    {"first_name": "Lindy", "last_name": "West", "email": "lwest@berkeley.edu", "role": "user"},
    {
        "first_name": "Julia",
        "last_name": "Jensen",
        "email": "046f34e75007810e0150ee35c6780940@ucsd.edu",
        "role": "user"
    },
    {
        "first_name": "Bhaskar",
        "last_name": "Sayyaparaju",
        "email": "bhaskar.sayyaparaju@kwartile.com ",
        "role": "user"
    },
    {"first_name": "Sreeram", "last_name": "Nyshadham", "email": "sreeram.nyshadham@kwartile.com", "role": "user"},
    {"first_name": "Sarah", "last_name": "Nunes", "email": "snunes@coh.org", "role": "user"},
    {"first_name": "Julie", "last_name": "Bautista", "email": "jubautista@coh.org", "role": "user"},
    {"first_name": "Noreen", "last_name": "Gaitan", "email": "ngaitan@uci.edu", "role": "user"},
    {"first_name": "Sameer", "last_name": "Karki", "email": "Sameer.Karki-ucop.edu@ucop.edu", "role": "user"},
    {"first_name": "Suman", "last_name": "Dhal", "email": "sdhal@ucdavis.edu", "role": "user"},
    {"first_name": "Russell", "last_name": "Shomberg", "email": "rshomberg@uri.edu", "role": "user"},
    {"first_name": "Anthony", "last_name": "Marshall", "email": "marshallan@my.uri.edu", "role": "user"},
    {"first_name": "Irine", "last_name": "Mforsoh", "email": "mforneba@uri.edu", "role": "user"},
    {"first_name": "Mary", "last_name": "Ward", "email": "wardm@mail.nih.gov", "role": "user"},
    {"first_name": "Michael", "last_name": "Wood", "email": "739668@ucsf.edu", "role": "user"},
    {"first_name": "Sonia", "last_name": "Guerrero-Rodriguez", "email": "alexis03@ucdavis.edu", "role": "user"},
    {"first_name": "Rena", "last_name": "Jones", "email": "rena.jones@nih.gov", "role": "user"},
    {"first_name": "Laura", "last_name": "Costas", "email": "laura.costas.ico@gmail.com", "role": "user"},
    {"first_name": "Evan", "last_name": "Walsh", "email": "ewalsh@ucsd.edu", "role": "user"},
    {"first_name": "Joy", "last_name": "Shi", "email": "joy_shi@harvard.edu", "role": "user"},
    {"first_name": "Mark", "last_name": "Powell", "email": "markp@zerobreastcancer.org", "role": "user"},
    {"first_name": "Theodore", "last_name": "Brasky", "email": "theodore.brasky@osumc.edu", "role": "user"},
    {"first_name": "Kimberly", "last_name": "Bernard", "email": "kimberlybernard@uri.edu", "role": "user"},
    {"first_name": "Dana", "last_name": "Brandt", "email": "dbrandt@uri.edu", "role": "user"},
    {"first_name": "Ariel", "last_name": "Neumann", "email": "aneumann@uri.edu", "role": "user"},
    {"first_name": "Dana", "last_name": "Brandt", "email": "dbrandt@uri.edu", "role": "user"},
    {"first_name": "David", "last_name": "Grenier", "email": "david_grenier@uri.edu", "role": "user"},
    {"first_name": "Joel", "last_name": "Stewart", "email": "jstewart@uri.edu", "role": "user"},
    {"first_name": "Kim", "last_name": "Pierson", "email": "kim_pierson@uri.edu", "role": "user"},
    {"first_name": "Li", "last_name": "Yuan", "email": "li_yuan@uri.edu", "role": "user"},
    {"first_name": "Megan", "last_name": "Swindal", "email": "mswindal@uri.edu", "role": "user"},
    {"first_name": "Melanie", "last_name": "Bowdish", "email": "melanie_bowdish@uri.edu", "role": "user"},
    {"first_name": "Yang", "last_name": "Xu", "email": "yang_xu@uri.edu", "role": "user"},
    {"first_name": "Mary", "last_name": "Maccree", "email": "malendia@ucdavis.edu", "role": "user"},
    {"first_name": "Bill", "last_name": "Collier", "email": "bcollier2@ucmerced.edu", "role": "user"},
    {"first_name": "Demetrius", "last_name": "Patrick", "email": "dimitrpa@ucr.edu", "role": "user"},
    {"first_name": "Laura", "last_name": "Zaruchaeva", "email": "laura.zaruchaeva@ucop.edu", "role": "user"},
    {"first_name": "Greg", "last_name": "Ryan", "email": "gryan@berkeley.edu", "role": "user"},
    {"first_name": "James", "last_name": "DeCamp", "email": "James.Decamp@ppsd.org", "role": "user"},
    {
        "first_name": "Dorothy",
        "last_name": "Fitzgerald",
        "email": "dorothy.fitzgerald@chariho.k12.ri.us",
        "role": "user"
    },
    {"first_name": "Dustin", "last_name": "Falke", "email": "dfalke@smithfield-ps.org", "role": "user"},
    {"first_name": "Mark", "last_name": "DiLuglio", "email": "mark.diluglio@scituateschoolsri.net", "role": "user"},
    {"first_name": "Carla", "last_name": "Batista", "email": "ms.batista@tapaprovidence.org", "role": "user"},
    {"first_name": "Rebekah", "last_name": "Gendron", "email": "rgendron@epschoolsri.com", "role": "user"},
    {"first_name": "Kate", "last_name": "Mills", "email": "katheryn.mills@bwrsd.org", "role": "user"},
    {"first_name": "Ada", "last_name": "Rojas", "email": "arojas@highlandercharter.org", "role": "user"},
    {"first_name": "Ann", "last_name": "Mariano", "email": "amariano@fgschools.com", "role": "user"},
    {"first_name": "Dave", "last_name": "Burrows", "email": "burrowsd@barringtonschools.org", "role": "user"},
    {"first_name": "Sheri", "last_name": "Thibeault", "email": "sthibeault@woonsocketschools.com", "role": "user"},
    {"first_name": "Jesse", "last_name": "Moore", "email": "jesse_moore@my.uri.edu", "role": "user"},
    {"first_name": "James", "last_name": "Miller", "email": "miller@uri.edu", "role": "user"},
    {"first_name": "Gopu", "last_name": "Potty", "email": "gpotty@uri.edu", "role": "user"},
    {"first_name": "Resit", "last_name": "Sendag", "email": "sendag@uri.edu", "role": "user"},
    {"first_name": "Manbir", "last_name": "Sodhi", "email": "sodhi@uri.edu", "role": "user"},
    {"first_name": "Michael", "last_name": "Riley", "email": "mriley5@ucmerced.edu", "role": "user"},
    {"first_name": "Megan", "last_name": "Clarke", "email": "megan.clarke@nih.gov", "role": "user"},
    {"first_name": "Trevor", "last_name": "Selby", "email": "tselby@ablschools.com", "role": "user"},
    {
        "first_name": "Amer",
        "last_name": "Heric",
        "email": "046f34e64ca3cdfb014d01d6816307b3@ucsd.edu",
        "role": "user"
    },
    {"first_name": "Xian-Bo", "last_name": "Wu", "email": "lfurong@smu.edu.cn", "role": "user"},
    {
        "first_name": "James",
        "last_name": "Gangwisch",
        "email": "james.gangwisch@nyspi.columbia.edu",
        "role": "user"
    },
    {"first_name": "Nikita", "last_name": "Wright", "email": "niwright@coh.org", "role": "user"},
    {"first_name": "James", "last_name": "Koh", "email": "james.koh@ucsf.edu", "role": "user"},
    {"first_name": "Hugo", "last_name": "Liang", "email": "Hugo.Liang@ucop.edu", "role": "user"},
    {"first_name": "John", "last_name": "Stringer", "email": "jstring@uri.edu", "role": "user"},
    {"first_name": "Gretchen", "last_name": "Scott", "email": "gretchens@berkeley.edu", "role": "user"},
    {"first_name": "Yan", "last_name": "Sun", "email": "yansun@uri.edu", "role": "user"},
    {"first_name": "Gabriel", "last_name": "DePace", "email": "gdepace@uri.edu", "role": "user"},
    {"first_name": "Monaye", "last_name": "Win", "email": "monay.win@ucop.edu", "role": "user"},
    {"first_name": "Anthony", "last_name": "Avalos", "email": "aavalos4230@ucla.edu", "role": "user"},
    {"first_name": "Brendan", "last_name": "Kelly", "email": "brendankelly@ucla.edu", "role": "user"},
    {"first_name": "Kevin", "last_name": "Wilson", "email": "kevin_wilson@brown.edu", "role": "user"},
    {"first_name": "Kimber", "last_name": "Barton", "email": "kbarton@ihpaco.org", "role": "user"},
    {"first_name": "Gujral", "last_name": "Madhusudan", "email": "mgujral@ucsd.edu", "role": "user"},
    {"first_name": "Angelle", "last_name": "Cheung", "email": "avcheung@ucdavis.edu", "role": "user"},
    {"first_name": "Matthew", "last_name": "Beckman", "email": "mjbeckman@ucdavis.edu", "role": "user"},
    {"first_name": "Nisin", "last_name": "Lwai", "email": "nisin.lwai@ucop.edu", "role": "user"},
    {"first_name": "Robin", "last_name": "Freeland", "email": "freelandr@uri.edu", "role": "user"},
    {"first_name": "Nidhi", "last_name": "Bodurtha", "email": "nidhi_mehta@uri.edu", "role": "user"},
    {"first_name": "Tyler", "last_name": "Chu", "email": "tylerchu@my.uri.edu", "role": "user"},
    {"first_name": "Brian", "last_name": "Aevermann", "email": "baeverma@jcvi.org", "role": "user"},
    {"first_name": "Radhadatta", "last_name": "Mahapatra", "email": "radmahap@in.ibm.com", "role": "user"},
    {"first_name": "Hardika", "last_name": "Bhasin", "email": "hardikabhasin@in.ibm.com", "role": "user"},
    {"first_name": "Matthew", "last_name": "Vanderbilt", "email": "mvanderbilt@ucsd.edu", "role": "user"},
    {"first_name": "Andrea", "last_name": "Sudharta", "email": "ahsudharta@ucsd.edu", "role": "user"},
    {"first_name": "Wanghuizi", "last_name": "Gao", "email": "w1gao@ucsd.edu", "role": "user"},
    {"first_name": "Shivakumar", "last_name": "Lanka", "email": "shivakumar.lanka@kwartile.com", "role": "user"},
    {"first_name": "Sarah", "last_name": "Jackson", "email": "sarah.jackson@nih.gov", "role": "user"},
    {"first_name": "Eng Wee Alvin", "last_name": "Gan", "email": "gan@ucdavis.edu", "role": "user"},
    {"first_name": "Erica", "last_name": "Olaguez", "email": "eolaguez@ucdavis.edu", "role": "user"},
    {"first_name": "Austin", "last_name": "Clark", "email": "austin_clark@my.uri.edu", "role": "user"},
    {"first_name": "Nan", "last_name": "Xiao", "email": "nan.xiao@sbgenomics.com", "role": "user"},
    {"first_name": "Jeremy", "last_name": "Hamilton", "email": "jrh823@berkeley.edu", "role": "user"},
    {"first_name": "Priya", "last_name": "Shah", "email": "prshah@berkeley.edu", "role": "user"},
    {"first_name": "Soheila", "last_name": "Khaligh", "email": "skhaligh@berkeley.edu", "role": "user"},
    {"first_name": "Eric", "last_name": "Miller", "email": "eric.miller2@nih.gov", "role": "user"},
    {"first_name": "Carl-Ernst", "last_name": "Rousseau", "email": "roussce@uri.edu", "role": "user"},
    {"first_name": "Chelsea", "last_name": "Fox", "email": "chelsea_fox@my.uri.edu", "role": "user"},
    {"first_name": "Makio", "last_name": "Tazawa", "email": "mtazawa@my.uri.edu", "role": "user"},
    {"first_name": "Phillip", "last_name": "Felgner", "email": "pfelgner@hs.uci.edu", "role": "user"},
    {"first_name": "Joshua", "last_name": "Demb", "email": "jdemb@ucsd.edu", "role": "user"},
    {"first_name": "Lohith", "last_name": "Potluri", "email": "lpotluri@health.ucsd.edu", "role": "user"},
    {"first_name": "Long", "last_name": "Zou", "email": "long_zou@my.uri.edu", "role": "user"},
    {"first_name": "Brennan", "last_name": "Phillips", "email": "brennanphillips@uri.edu", "role": "user"},
    {"first_name": "Forgive", "last_name": "Avorgbedor", "email": "avorgbe@live.unc.edu", "role": "user"},
    {"first_name": "Jeffrey", "last_name": "Massin", "email": "jeffrey.massin@cgu.edu", "role": "user"},
    {"first_name": "Siena", "last_name": "Schmitt", "email": "siena.rapetti@cgu.edu", "role": "user"},
    {"first_name": "Hazel", "last_name": "Escusa", "email": "hazel.escusa@cgu.edu", "role": "user"},
    {"first_name": "Willard", "last_name": "Simoneau", "email": "wsimoneau@uri.edu", "role": "user"},
    {"first_name": "Pei-Ru", "last_name": "Chao", "email": "peiru.chao@ucop.edu", "role": "user"},
    {"first_name": "Veronica", "last_name": "Luna", "email": "vluna@ucr.edu", "role": "user"},
    {"first_name": "Tina", "last_name": "Jackson", "email": "tejackson@ucla.edu", "role": "user"},
    {"first_name": "Sean", "last_name": "Villa-Carlos", "email": "sean.villa-carlos@ucop.edu", "role": "user"},
    {"first_name": "Samson", "last_name": "Bali", "email": "samson.bali@ucop.edu", "role": "user"},
    {"first_name": "Jenny", "last_name": "Zhang", "email": "jenny.zhang@ucop.edu", "role": "user"},
    {"first_name": "Shawn", "last_name": "Aguilar", "email": "shawn.aguilst@ucop.edu", "role": "user"},
    {"first_name": "Arijit", "last_name": "Bose", "email": "bosea@uri.edu", "role": "user"},
    {"first_name": "Joseph", "last_name": "Sullivan", "email": "josephsullivan@my.uri.edu", "role": "user"},
    {"first_name": "Scott", "last_name": "Tebbutt", "email": "Scott.Tebbutt@hli.ubc.ca", "role": "user"},
    {"first_name": "Casey", "last_name": "Shannon", "email": "casey.shannon@hli.ubc.ca", "role": "user"},
    {"first_name": "Janette", "last_name": "Ducut", "email": "janetted@ucr.edu", "role": "user"},
    {"first_name": "Erich", "last_name": "Huebner", "email": "ehuebner@ucsd.edu", "role": "user"},
    {"first_name": "Pascal", "last_name": "Meunier", "email": "pmeunier@purdue.edu", "role": "user"},
    {"first_name": "Luke", "last_name": "Watkins", "email": "luke_watkins@my.uri.edu", "role": "user"},
    {"first_name": "Gabriella", "last_name": "Aiello", "email": "gaiello@uri.edu", "role": "user"},
    {"first_name": "Vivianna", "last_name": "Cid", "email": "viviannakc@ucla.edu", "role": "user"},
    {"first_name": "Stephen", "last_name": "Furman", "email": "sfurman@berkeley.edu", "role": "user"},
    {"first_name": "Christopher", "last_name": "Baxter", "email": "cbaxter@uri.edu", "role": "user"},
    {"first_name": "Lora Van", "last_name": "Uffelen", "email": "loravu@uri.edu", "role": "user"},
    {"first_name": "Dillon", "last_name": "Fontaine", "email": "dtf2002@uri.edu", "role": "user"},
    {"first_name": "Patrick", "last_name": "Kaulback", "email": "pkaulback@berkeley.edu", "role": "user"},
    {"first_name": "Ezra Van", "last_name": "Everbroeck", "email": "ezra@ucsd.edu", "role": "user"},
    {"first_name": "Tod", "last_name": "Kuykendall", "email": "t2kuykendall@ucsd.edu", "role": "user"},
    {"first_name": "Steven", "last_name": "Clark", "email": "smclark@ucsd.edu", "role": "user"},
    {"first_name": "Nicholas", "last_name": "Kisseberth", "email": "nkisseberth@ucsd.edu", "role": "user"},
    {"first_name": "Sukrit", "last_name": "Mukherjee", "email": "sukritmukherjee@cdrewu.edu", "role": "user"},
    {"first_name": "Ian", "last_name": "Heino", "email": "ian_heino@my.uri.edu", "role": "user"},
    {"first_name": "Jocelyn", "last_name": "Dorsey", "email": "jdorsey@berkeley.edu", "role": "user"},
    {"first_name": "Maria", "last_name": "Espinoza", "email": "mz2697@cumc.columbia.edu", "role": "user"},
    {"first_name": "Sarah", "last_name": "Tom", "email": "st3144@cumc.columbia.edu", "role": "user"},
    {"first_name": "Greer", "last_name": "Gustavson", "email": "Greer.Gustavson-ucop.edu@ucop.edu", "role": "user"},
    {"first_name": "Richard", "last_name": "Vaccaro", "email": "vaccaro@uri.edu", "role": "user"},
    {"first_name": "Austin", "last_name": "Conte", "email": "austin_conte@my.uri.edu", "role": "user"},
    {"first_name": "Sam", "last_name": "Park", "email": "sapark@health.ucsd.edu", "role": "user"},
    {"first_name": "Laila", "last_name": "Al-Shaar", "email": "lalshaar@hsph.harvard.edu", "role": "user"},
    {"first_name": "Ruifeng", "last_name": "Li", "email": "rli@hsph.harvard.edu", "role": "user"},
    {"first_name": "Jennifer", "last_name": "Yeager", "email": "jyeager@ucsc.edu", "role": "user"},
    {"first_name": "Eugene", "last_name": "Tucker", "email": "ETucker@lbl.gov", "role": "user"},
    {
        "first_name": "Hariprasad",
        "last_name": "Madas",
        "email": "Hariprasad.Madas-ucop.edu@ucop.edu",
        "role": "user"
    },
    {"first_name": "Barbra", "last_name": "Ross", "email": "bross@ucdavis.edu", "role": "user"},
    {"first_name": "Abigail", "last_name": "Flory", "email": "abigail.flory@nih.gov", "role": "user"},
    {"first_name": "Steven", "last_name": "Blair", "email": "smblair@ucsd.edu", "role": "user"},
    {"first_name": "Xiaolu", "last_name": "Zhang-Gross", "email": "azhang@hsph.harvard.edu", "role": "user"},
    {"first_name": "Adam", "last_name": "Burkholder", "email": "ajburk@ucdavis.edu", "role": "user"},
    {"first_name": "Helio", "last_name": "Matos", "email": "hmatos@uri.edu", "role": "user"},
    {"first_name": "Shiaw-Shyuan (Sherry)", "last_name": "Yaun", "email": "syaun@hsph.harvard.edu", "role": "user"},
    {"first_name": "April", "last_name": "Fraizer", "email": "afrazier@lji.org", "role": "user"},
    {"first_name": "Alessandro", "last_name": "Sette", "email": "alex@lji.org", "role": "user"},
    {"first_name": "Julianna", "last_name": "Han", "email": "juliannahan@scripps.edu", "role": "user"},
    {"first_name": "Bob", "last_name": "Hancock", "email": "bob@hancocklab.com", "role": "user"},
    {"first_name": "Derek", "last_name": "Cridebring", "email": "dcridebring@tgen.org", "role": "user"},
    {"first_name": "Sumair", "last_name": "Sajid", "email": "sumair.sajid@ucop.edu", "role": "user"},
    {
        "first_name": "Hima Bindu",
        "last_name": "Patlolla",
        "email": "Hima.Patlolla-ucop.edu@ucop.edu",
        "role": "user"
    },
    {"first_name": "Radhadatta", "last_name": "Mahapatra", "email": "radmahap@in.ibm.com", "role": "user"},
    {"first_name": "Glenn", "last_name": "Glasgow", "email": "gglasgow@ucdavis.edu", "role": "user"},
    {"first_name": "Ilona", "last_name": "Kabara", "email": "ilona.kabara@nih.gov", "role": "user"},
    {"first_name": "Bhanupriya", "last_name": "Gudimetla", "email": "bhanupriya.g@in.ibm.com", "role": "user"},
    {"first_name": "Chintan", "last_name": "Sodha", "email": "Chintan.Sodha-ucop.edu@ucop.edu", "role": "user"},
    {"first_name": "Jamie", "last_name": "Russell", "email": "jlrussel@ucdavis.edu", "role": "user"},
    {"first_name": "Josh", "last_name": "Spears", "email": "j.dspears@yahoo.com", "role": "user"},
    {"first_name": "Sumair", "last_name": "Sajid", "email": "ssajid2@dms.local", "role": "user"},
    {"first_name": "Kai", "last_name": "Lin", "email": "klin@sdsc.edu", "role": "user"},
    {"first_name": "Ilya", "last_name": "Shunko", "email": "ishunko@sdsc.edu", "role": "user"},
    {"first_name": "James", "last_name": "Graves", "email": "jbgraves@ucsd.edu", "role": "user"},
    {"first_name": "Damion", "last_name": "Junk", "email": "djunk@sdsc.edu", "role": "user"},
    {"first_name": "Tony", "last_name": "Chen", "email": "t9chen@ucsd.edu", "role": "user"},
    {"first_name": "Carol", "last_name": "Brothers", "email": "carol.brothers@ucop.edu", "role": "user"},
    {"first_name": "Su-Ho", "last_name": "Hwang", "email": "shwang@deepthinkhealth.com", "role": "user"},
    {"first_name": "Stefanie", "last_name": "Yoshii", "email": "syoshi@uci.edu", "role": "user"},
    {"first_name": "Grace", "last_name": "Aldrovandi", "email": "galdrovandi@mednet.ucla.edu", "role": "user"},
    {"first_name": "Larry", "last_name": "Wong", "email": "Larry.Wong-ucop.edu@ucop.edu", "role": "user"},
    {"first_name": "Cindi", "last_name": "Zimmerman", "email": "czimmerman3@ucmerced.edu", "role": "user"},
    {"first_name": "Mahidhar", "last_name": "Tatineni", "email": "mahidhar@sdsc.edu", "role": "user"},
    {"first_name": "Christopher", "last_name": "Irving", "email": "cirving@ucsd.edu", "role": "user"},
    {"first_name": "Aayush", "last_name": "Kunwar", "email": "aayush.kunwar@ucop.edu", "role": "user"},
    {"first_name": "Michael", "last_name": "Chand", "email": "mchand@berkeley.edu", "role": "user"},
    {"first_name": "Charleston", "last_name": "Chiang", "email": "charleston.chiang@med.usc.edu", "role": "user"},
    {"first_name": "Anthony", "last_name": "Fuentes", "email": "acfuentes@sdsc.edu", "role": "user"},
    {"first_name": "Paul", "last_name": "Norton", "email": "panorton@ucsd.edu", "role": "user"},
    {"first_name": "Pagan", "last_name": "Morris", "email": "Pagan.Morris-ucop.edu@ucop.edu", "role": "user"},
    {"first_name": "Chandima", "last_name": "Hewanadungodage", "email": "chewanad@purdue.edu", "role": "user"},
    {"first_name": "Andres", "last_name": "Bejarano", "email": "abejara@purdue.edu", "role": "user"},
    {"first_name": "Migel", "last_name": "Dio", "email": "migel.dio@berkeley.edu", "role": "user"},
    {"first_name": "Davd", "last_name": "Ensberg (Duo)", "email": "densberg@ucsd.edu", "role": "user"},
    {"first_name": "Matthew", "last_name": "Leger", "email": "matthew_leger@my.uri.edu", "role": "user"},
    {"first_name": "Ann Christine", "last_name": "Catlin", "email": "acc@purdue.edu", "role": "user"},
    {"first_name": "Sumudinie", "last_name": "Fernando", "email": "sumudinie@gmail.com", "role": "user"},
    {"first_name": "Guneshi", "last_name": "Wickramaarachchi", "email": "gwickram@purdue.edu", "role": "user"},
    {"first_name": "Keehwan", "last_name": "Park", "email": "park451@purdue.edu", "role": "user"},
    {"first_name": "Caroline", "last_name": "Thompson", "email": "caroline.thompson@sdsu.edu", "role": "user"},
    {"first_name": "Melissa", "last_name": "Burley", "email": "Melissa.Burley-ucop.edu@ucop.edu", "role": "user"},
    {"first_name": "Reena", "last_name": "Joseph", "email": "reejo@ucdavis.edu", "role": "user"},
    {"first_name": "Lisa", "last_name": "Gallicchio", "email": "lisa.gallicchio@nih.gov", "role": "user"},
    {"first_name": "Jeff", "last_name": "Kayser", "email": "jkayser@sdsc.edu", "role": "user"},
    {"first_name": "Laura", "last_name": "Thompson", "email": "lkthomps@usc.edu", "role": "user"},
    {"first_name": "Michael", "last_name": "Galang", "email": "mbgalang@ucdavis.edu", "role": "user"},
    {"first_name": "Valentina", "last_name": "Rossell-Olmos", "email": "vrossell@my.uri.edu", "role": "user"},
    {"first_name": "Mark", "last_name": "Keenan", "email": "mark_keenan@my.uri.edu", "role": "user"},
    {"first_name": "Sam", "last_name": "Wing", "email": "swing@coh.org", "role": "user"},
    {"first_name": "Jerry", "last_name": "Wilson", "email": "jfw3520@ucla.edu", "role": "user"},
    {"first_name": "Stephen", "last_name": "Collins", "email": "uclasteve@ucla.edu", "role": "user"},
    {"first_name": "Brian", "last_name": "Caferro", "email": "brian_caferro@my.uri.edu", "role": "user"},
    {"first_name": "Albert", "last_name": "Larson", "email": "albertl@uri.edu", "role": "user"},
    {"first_name": "Jonas", "last_name": "Baltazar", "email": "806349@ucsf.edu", "role": "user"},
    {"first_name": "Andrew", "last_name": "Bindner", "email": "cteklab1@ucla.edu", "role": "user"}
];


let all_users = [];
for (var i=0; i<users.length; i++) {
    let found = false;
    for (var j=i+1; j<users.length; j++ ) {
        if (JSON.stringify(users[i]) === JSON.stringify(users[j])) {
            found = true;
        }
    }
    if (!found) {
        all_users.push(users[i]);
    }
}


module.exports = all_users;

